name: mapmetrics
description: "Permissive and performant mapping library that supports Mapbox Vector Tiles (MVT) powered by MapLibre SDKs."
version: 0.0.8
repository: https://github.com/MapMetrics/MapMetrics-flutter
issue_tracker: https://github.com/MapMetrics/MapMetrics-flutter/issues
#homepage: https://flutter-maplibre.pages.dev
#documentation: https://flutter-maplibre.pages.dev/docs/index/
publish_to: null

topics: [ map, mapmetrics, mvt ]

platforms:
  android:
  ios:
  web:

environment:
  flutter: ^3.29.0
  sdk: ^3.7.0

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  geotypes: ^0.0.2
  html: ^0.15.4
  jni: ^0.14.0
#  maplibre_ios:
#    path: maplibre_ios
  objective_c: ^6.0.0
  pointer_interceptor: ^0.10.1+2
  url_launcher: ^6.3.0
  web: ^1.0.0

dev_dependencies:

  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  jnigen: ^0.14.0
  mocktail: ^1.0.4
  pigeon: ^24.0.0
  very_good_analysis: ^7.0.0

screenshots:
  - description: 'MapMetrics Logo'
    path: 'doc/logo_rounded.png'

flutter:
  plugin:
    platforms:
      android:
        package: com.github.mapmetrics.maplibre
        pluginClass: MapLibrePlugin
      ios:
        pluginClass: MapLibreIosPlugin
      linux:
        pluginClass: MaplibrePlugin
      macos:
        pluginClass: MaplibrePlugin
      windows:
        pluginClass: MaplibrePluginCApi
      web:
        pluginClass: PlatformImpl
        fileName: src/platform/platform_web.dart

ffigen:
  name: MapLibreFFi
  description: Bindings for MapLibre iOS.
  language: objc
  output: 'lib/platform/maplibre_ffi.dart'
  exclude-all-by-default: true
  objc-interfaces:
    include:
      - 'NSString'
      - 'MapLibreRegistry'
      - 'MLNMapView'
      - 'MLNMapCamera'
      - 'CLLocationCoordinate2D'
      - 'MLNMapProjection'
      - 'MLNStyle'
      - 'MLNSource'
      - 'MLNRasterTileSource'
      - 'MLNVectorTileSource'
      - 'MLNImageSource'
      - 'MLNRasterDEMSource'
      - 'MLNVectorTileSource'
      - 'MLNBackgroundStyleLayer'
      - 'MLNCircleStyleLayer'
      - 'MLNFillExtrusionStyleLayer'
      - 'MLNFillStyleLayer'
      - 'MLNHeatmapStyleLayer'
      - 'MLNHillshadeStyleLayer'
      - 'MLNLineStyleLayer'
      - 'MLNRasterStyleLayer'
      - 'MLNSymbolStyleLayer'
      - 'MLNVectorStyleLayer'
      - 'MLNAttributionInfo'
      - 'NSAttributedString'
      - 'MLNShapeSource'
      - 'MLNImageSource'
      - 'MLNShape'
      - 'MLNRasterDEMSource'
      - 'MLNOfflineStorage'
      - 'MLNTilePyramidOfflineRegion'
      - 'MLNOfflinePack'
      - 'MLNOfflineRegion'
      - 'MLNTilePyramidOfflineRegion'
      - 'NSImage'
      - 'NSExpression'
      - 'Helpers'
    module:
      'MapLibreRegistry': 'mapmetrics'
      'Helpers': 'mapmetrics'
      'MLNMapView': 'MapLibre'
      'MLNMapCamera': 'MapLibre'
      'MLNVectorTileSource': 'MapLibre'
      'MLNOfflinePack': 'MapLibre'
      'MLNOfflineRegion': 'MapLibre'
  headers:
    entry-points:
      - 'ios/mapmetrics/Sources/maplibre_ios/MapLibreRegistry.h'
      - 'ios/mapmetrics/Sources/maplibre_ios/Helpers.h'
      # using the MapLibre.h file doesn't seem to work
      # TODO find a better solution for the entry points
      #- '/Users/joscha/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MapLibre.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNMapView.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNMapProjection.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNStyle.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNSource.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNVectorTileSource.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNComputedShapeSource.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNImageSource.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNRasterTileSource.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNRasterDEMSource.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNBackgroundStyleLayer.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNCircleStyleLayer.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNFillExtrusionStyleLayer.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNFillStyleLayer.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNHeatmapStyleLayer.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNHillshadeStyleLayer.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNLineStyleLayer.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNRasterStyleLayer.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNSymbolStyleLayer.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNVectorStyleLayer.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNAttributionInfo.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/NSExpression+MLNAdditions.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNOfflineStorage.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNOfflinePack.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNOfflineRegion.h'
      - '/Users/macbook/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers/MLNTilePyramidOfflineRegion.h'
      #include-directives:
      #- '~/Library/Caches/CocoaPods/Pods/Release/MapLibre/6.11.0-9ff4b/MapLibre.xcframework/ios-arm64_x86_64-simulator/MapLibre.framework/Headers'
  preamble: |
    // ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field, return_of_invalid_type, void_checks, annotate_overrides, no_leading_underscores_for_local_identifiers, library_private_types_in_public_api