// swiftformat:disable all
// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Influences the y direction of the tile coordinates. */
enum class TileScheme(val raw: Int) {
  /** Slippy map tilenames scheme. */
  XYZ(0),
  /** OSGeo spec scheme. */
  TMS(1);

  companion object {
    fun ofRaw(raw: Int): TileScheme? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The encoding used by this source. Mapbox Terrain RGB is used by default. */
enum class RasterDemEncoding(val raw: Int) {
  /** Terrarium format PNG tiles. */
  TERRARIUM(0),
  /** Mapbox Terrain RGB tiles. */
  MAPBOX(1),
  /**
   * Decodes tiles using the redFactor, blueFactor, greenFactor, baseShift
   * parameters.
   */
  CUSTOM(2);

  companion object {
    fun ofRaw(raw: Int): RasterDemEncoding? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The reason the camera is changing. */
enum class CameraChangeReason(val raw: Int) {
  /** Developer animation. */
  DEVELOPER_ANIMATION(0),
  /** API animation. */
  API_ANIMATION(1),
  /** API gesture */
  API_GESTURE(2);

  companion object {
    fun ofRaw(raw: Int): CameraChangeReason? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A longitude/latitude coordinate object.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LngLat (
  /** The longitude */
  val lng: Double,
  /** The latitude */
  val lat: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LngLat {
      val lng = pigeonVar_list[0] as Double
      val lat = pigeonVar_list[1] as Double
      return LngLat(lng, lat)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lng,
      lat,
    )
  }
}

/**
 * The map options define initial values for the MapLibre map.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MapOptions (
  /** The URL of the used map style. */
  val style: String,
  /** The initial zoom level of the map. */
  val zoom: Double,
  /** The initial pitch / tilt of the map. */
  val pitch: Double,
  /** The initial bearing of the map. */
  val bearing: Double,
  /** The initial center coordinates of the map. */
  val center: LngLat? = null,
  /** The maximum bounding box of the map camera. */
  val maxBounds: LngLatBounds? = null,
  /** The minimum zoom level of the map. */
  val minZoom: Double,
  /** The maximum zoom level of the map. */
  val maxZoom: Double,
  /** The minimum pitch / tilt of the map. */
  val minPitch: Double,
  /** The maximum pitch / tilt of the map. */
  val maxPitch: Double,
  /** The map gestures. */
  val gestures: MapGestures,
  /** Toggle the texture mode on android. */
  val androidTextureMode: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MapOptions {
      val style = pigeonVar_list[0] as String
      val zoom = pigeonVar_list[1] as Double
      val pitch = pigeonVar_list[2] as Double
      val bearing = pigeonVar_list[3] as Double
      val center = pigeonVar_list[4] as LngLat?
      val maxBounds = pigeonVar_list[5] as LngLatBounds?
      val minZoom = pigeonVar_list[6] as Double
      val maxZoom = pigeonVar_list[7] as Double
      val minPitch = pigeonVar_list[8] as Double
      val maxPitch = pigeonVar_list[9] as Double
      val gestures = pigeonVar_list[10] as MapGestures
      val androidTextureMode = pigeonVar_list[11] as Boolean
      return MapOptions(style, zoom, pitch, bearing, center, maxBounds, minZoom, maxZoom, minPitch, maxPitch, gestures, androidTextureMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      style,
      zoom,
      pitch,
      bearing,
      center,
      maxBounds,
      minZoom,
      maxZoom,
      minPitch,
      maxPitch,
      gestures,
      androidTextureMode,
    )
  }
}

/**
 * Map gestures
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MapGestures (
  /** Rotate the map bearing. */
  val rotate: Boolean,
  /** Move the center of the map around. */
  val pan: Boolean,
  /** Zoom the map in and out. */
  val zoom: Boolean,
  /** Tilt (pitch) the map camera. */
  val tilt: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MapGestures {
      val rotate = pigeonVar_list[0] as Boolean
      val pan = pigeonVar_list[1] as Boolean
      val zoom = pigeonVar_list[2] as Boolean
      val tilt = pigeonVar_list[3] as Boolean
      return MapGestures(rotate, pan, zoom, tilt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rotate,
      pan,
      zoom,
      tilt,
    )
  }
}

/**
 * A pixel location / location on the device screen.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Offset (
  /** The x coordinate */
  val x: Double,
  /** The y coordinate */
  val y: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Offset {
      val x = pigeonVar_list[0] as Double
      val y = pigeonVar_list[1] as Double
      return Offset(x, y)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
    )
  }
}

/**
 * Camera Padding
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Padding (
  val top: Long,
  val bottom: Long,
  val left: Long,
  val right: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Padding {
      val top = pigeonVar_list[0] as Long
      val bottom = pigeonVar_list[1] as Long
      val left = pigeonVar_list[2] as Long
      val right = pigeonVar_list[3] as Long
      return Padding(top, bottom, left, right)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      top,
      bottom,
      left,
      right,
    )
  }
}

/**
 * The current position of the map camera.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MapCamera (
  val center: LngLat,
  val zoom: Double,
  val pitch: Double,
  val bearing: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MapCamera {
      val center = pigeonVar_list[0] as LngLat
      val zoom = pigeonVar_list[1] as Double
      val pitch = pigeonVar_list[2] as Double
      val bearing = pigeonVar_list[3] as Double
      return MapCamera(center, zoom, pitch, bearing)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      center,
      zoom,
      pitch,
      bearing,
    )
  }
}

/**
 * LatLng bound object
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LngLatBounds (
  val longitudeWest: Double,
  val longitudeEast: Double,
  val latitudeSouth: Double,
  val latitudeNorth: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LngLatBounds {
      val longitudeWest = pigeonVar_list[0] as Double
      val longitudeEast = pigeonVar_list[1] as Double
      val latitudeSouth = pigeonVar_list[2] as Double
      val latitudeNorth = pigeonVar_list[3] as Double
      return LngLatBounds(longitudeWest, longitudeEast, latitudeSouth, latitudeNorth)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      longitudeWest,
      longitudeEast,
      latitudeSouth,
      latitudeNorth,
    )
  }
}

/**
 * Model that describes an offline map region.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OfflineRegion (
  val id: Long,
  val bounds: LngLatBounds,
  val minZoom: Double,
  val maxZoom: Double,
  val pixelRatio: Double,
  val styleUrl: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OfflineRegion {
      val id = pigeonVar_list[0] as Long
      val bounds = pigeonVar_list[1] as LngLatBounds
      val minZoom = pigeonVar_list[2] as Double
      val maxZoom = pigeonVar_list[3] as Double
      val pixelRatio = pigeonVar_list[4] as Double
      val styleUrl = pigeonVar_list[5] as String
      return OfflineRegion(id, bounds, minZoom, maxZoom, pixelRatio, styleUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      bounds,
      minZoom,
      maxZoom,
      pixelRatio,
      styleUrl,
    )
  }
}
private open class PigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TileScheme.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RasterDemEncoding.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraChangeReason.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LngLat.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MapOptions.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MapGestures.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Offset.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Padding.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MapCamera.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LngLatBounds.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OfflineRegion.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TileScheme -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is RasterDemEncoding -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is CameraChangeReason -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is LngLat -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is MapOptions -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is MapGestures -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is Offset -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is Padding -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is MapCamera -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is LngLatBounds -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is OfflineRegion -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MapLibreHostApi {
  fun dispose()
  /** Add a fill layer to the map style. */
  fun addFillLayer(id: String, sourceId: String, layout: Map<String, Any>, paint: Map<String, Any>, belowLayerId: String?, callback: (Result<Unit>) -> Unit)
  /** Add a circle layer to the map style. */
  fun addCircleLayer(id: String, sourceId: String, layout: Map<String, Any>, paint: Map<String, Any>, belowLayerId: String?, callback: (Result<Unit>) -> Unit)
  /** Add a background layer to the map style. */
  fun addBackgroundLayer(id: String, layout: Map<String, Any>, paint: Map<String, Any>, belowLayerId: String?, callback: (Result<Unit>) -> Unit)
  /** Add a fill extrusion layer to the map style. */
  fun addFillExtrusionLayer(id: String, sourceId: String, layout: Map<String, Any>, paint: Map<String, Any>, belowLayerId: String?, callback: (Result<Unit>) -> Unit)
  /** Add a heatmap layer to the map style. */
  fun addHeatmapLayer(id: String, sourceId: String, layout: Map<String, Any>, paint: Map<String, Any>, belowLayerId: String?, callback: (Result<Unit>) -> Unit)
  /** Add a hillshade layer to the map style. */
  fun addHillshadeLayer(id: String, sourceId: String, layout: Map<String, Any>, paint: Map<String, Any>, belowLayerId: String?, callback: (Result<Unit>) -> Unit)
  /** Add a line layer to the map style. */
  fun addLineLayer(id: String, sourceId: String, layout: Map<String, Any>, paint: Map<String, Any>, belowLayerId: String?, callback: (Result<Unit>) -> Unit)
  /** Add a raster layer to the map style. */
  fun addRasterLayer(id: String, sourceId: String, layout: Map<String, Any>, paint: Map<String, Any>, belowLayerId: String?, callback: (Result<Unit>) -> Unit)
  /** Add a symbol layer to the map style. */
  fun addSymbolLayer(id: String, sourceId: String, layout: Map<String, Any>, paint: Map<String, Any>, belowLayerId: String?, callback: (Result<Unit>) -> Unit)
  /**
   * Loads an image to the map. An image needs to be loaded before it can
   * get used.
   */
  fun loadImage(url: String, callback: (Result<ByteArray>) -> Unit)
  /** Add an image to the map. */
  fun addImage(id: String, bytes: ByteArray, callback: (Result<Unit>) -> Unit)
  /**
   * Add multiple images to the map in a single batch operation.
   * This is significantly faster than calling addImage multiple times.
   */
  fun addImages(ids: List<String>, images: List<ByteArray>, callback: (Result<Unit>) -> Unit)
  /**
   * Load a sprite sheet and add all icons to the map in a single native operation.
   * This is the fastest way to load many icons - all extraction happens natively.
   * spriteJson: The sprite.json content as a string
   * spriteImage: The sprite.png as bytes
   */
  fun addSprite(spriteJson: String, spriteImage: ByteArray, callback: (Result<Unit>) -> Unit)
  /** Add a GeoJSON source with clustering to the map style. */
  fun addClusteredGeoJsonSource(id: String, data: String, clustered: Boolean, clusterRadius: Double, clusterMaxZoom: Double, clusterPropertiesJson: String?, callback: (Result<Unit>) -> Unit)
  /** Add a vector source to the map style. */
  fun addVectorSource(id: String, tiles: List<String>, minZoom: Double, maxZoom: Double, callback: (Result<Unit>) -> Unit)
  /** Minimal test method to debug Pigeon generation. */
  fun testMethod(value: String, callback: (Result<Unit>) -> Unit)
  /**
   * Animate the camera to a new position.
   * Use -1.0 or double.nan for any value you do not want to change.
   */
  fun animateCamera(latitude: Double, longitude: Double, zoom: Double, bearing: Double, pitch: Double, duration: Long, callback: (Result<Unit>) -> Unit)
  /** Get the current camera state. */
  fun getCamera(): MapCamera
  /** Get the current zoom level. */
  fun getZoomLevel(): Double
  /** Get the user's current location. */
  fun getUserLocation(): LngLat
  /**
   * Move the camera to a new position without animation.
   * Use -1.0 or double.nan for any value you do not want to change.
   */
  fun moveCamera(lat: Double, lng: Double, zoom: Double, bearing: Double, pitch: Double, callback: (Result<Unit>) -> Unit)
  /** Update map options including bounds and gesture settings. */
  fun updateMapOptions(minZoom: Double, maxZoom: Double, minPitch: Double, maxPitch: Double, boundsWest: Double, boundsSouth: Double, boundsEast: Double, boundsNorth: Double, rotateEnabled: Boolean, panEnabled: Boolean, zoomEnabled: Boolean, pitchEnabled: Boolean, callback: (Result<Unit>) -> Unit)
  /** Enable location services and show user location on map. */
  fun enableLocation(fastestInterval: Long, maxWaitTime: Long, pulseFade: Boolean, accuracyAnimation: Boolean, compassAnimation: Boolean, pulse: Boolean, callback: (Result<Unit>) -> Unit)
  /** Fit the map camera to show the specified bounds. */
  fun fitBounds(west: Double, south: Double, east: Double, north: Double, bearing: Double, pitch: Double, duration: Long, paddingLeft: Double, paddingTop: Double, paddingRight: Double, paddingBottom: Double, callback: (Result<Unit>) -> Unit)
  /**
   * Set the persistent viewport content inset (in logical pixels). After this
   * call, ALL subsequent camera operations (moveCamera, animateCamera, etc.)
   * treat the inset rectangle as the effective viewport — the camera `center`
   * lat/lng projects to the geometric center of that rectangle, and bearing
   * pivots around it. Used for navigation to keep the user puck low on screen
   * while ensuring rotation pivots through the puck.
   */
  fun setContentInset(left: Double, top: Double, right: Double, bottom: Double, callback: (Result<Unit>) -> Unit)
  /** Get the meters per pixel at the specified latitude. */
  fun getMetersPerPixelAtLatitude(latitude: Double, callback: (Result<Double>) -> Unit)
  /**
   * Get the visible region bounds.
   * Returns [west, south, east, north]
   */
  fun getVisibleRegion(callback: (Result<List<Double>>) -> Unit)
  /**
   * Convert screen coordinates to longitude/latitude.
   * Returns [lng, lat]
   */
  fun toLngLat(x: Double, y: Double, callback: (Result<List<Double>>) -> Unit)
  /**
   * Convert longitude/latitude to screen coordinates.
   * Returns [x, y]
   */
  fun toScreenLocation(lng: Double, lat: Double, callback: (Result<List<Double>>) -> Unit)
  /** Query rendered layers at the specified screen location. */
  fun queryLayers(x: Double, y: Double, callback: (Result<List<Map<String, String>>>) -> Unit)
  /**
   * Query rendered layers within a bounding box (more efficient for hit detection).
   * [left], [top], [right], [bottom] define the screen-space bounding box.
   * Returns list of maps (Object? used for platform compatibility).
   */
  fun queryLayersInRect(left: Double, top: Double, right: Double, bottom: Double, callback: (Result<List<Map<Any?, Any?>>>) -> Unit)
  /** Enable/disable location tracking with bearing mode. */
  fun trackLocation(track: Boolean, bearingMode: Long, callback: (Result<Unit>) -> Unit)
  /** Show/hide the user location puck (blue dot). */
  fun showUserLocationPuck(show: Boolean, callback: (Result<Unit>) -> Unit)
  fun removeLayer(id: String, callback: (Result<Unit>) -> Unit)
  fun removeSource(id: String, callback: (Result<Unit>) -> Unit)
  fun updateGeoJsonSource(id: String, data: String, callback: (Result<Unit>) -> Unit)
  /**
   * Switch the map style in-place without destroying the map.
   * This avoids the native SIGSEGV that occurs when the map widget is
   * destroyed while GeoJSON messages are still queued on the Looper.
   */
  fun setStyleUri(styleUri: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by MapLibreHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `MapLibreHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MapLibreHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dispose()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addFillLayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val sourceIdArg = args[1] as String
            val layoutArg = args[2] as Map<String, Any>
            val paintArg = args[3] as Map<String, Any>
            val belowLayerIdArg = args[4] as String?
            api.addFillLayer(idArg, sourceIdArg, layoutArg, paintArg, belowLayerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addCircleLayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val sourceIdArg = args[1] as String
            val layoutArg = args[2] as Map<String, Any>
            val paintArg = args[3] as Map<String, Any>
            val belowLayerIdArg = args[4] as String?
            api.addCircleLayer(idArg, sourceIdArg, layoutArg, paintArg, belowLayerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addBackgroundLayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val layoutArg = args[1] as Map<String, Any>
            val paintArg = args[2] as Map<String, Any>
            val belowLayerIdArg = args[3] as String?
            api.addBackgroundLayer(idArg, layoutArg, paintArg, belowLayerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addFillExtrusionLayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val sourceIdArg = args[1] as String
            val layoutArg = args[2] as Map<String, Any>
            val paintArg = args[3] as Map<String, Any>
            val belowLayerIdArg = args[4] as String?
            api.addFillExtrusionLayer(idArg, sourceIdArg, layoutArg, paintArg, belowLayerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addHeatmapLayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val sourceIdArg = args[1] as String
            val layoutArg = args[2] as Map<String, Any>
            val paintArg = args[3] as Map<String, Any>
            val belowLayerIdArg = args[4] as String?
            api.addHeatmapLayer(idArg, sourceIdArg, layoutArg, paintArg, belowLayerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addHillshadeLayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val sourceIdArg = args[1] as String
            val layoutArg = args[2] as Map<String, Any>
            val paintArg = args[3] as Map<String, Any>
            val belowLayerIdArg = args[4] as String?
            api.addHillshadeLayer(idArg, sourceIdArg, layoutArg, paintArg, belowLayerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addLineLayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val sourceIdArg = args[1] as String
            val layoutArg = args[2] as Map<String, Any>
            val paintArg = args[3] as Map<String, Any>
            val belowLayerIdArg = args[4] as String?
            api.addLineLayer(idArg, sourceIdArg, layoutArg, paintArg, belowLayerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addRasterLayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val sourceIdArg = args[1] as String
            val layoutArg = args[2] as Map<String, Any>
            val paintArg = args[3] as Map<String, Any>
            val belowLayerIdArg = args[4] as String?
            api.addRasterLayer(idArg, sourceIdArg, layoutArg, paintArg, belowLayerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addSymbolLayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val sourceIdArg = args[1] as String
            val layoutArg = args[2] as Map<String, Any>
            val paintArg = args[3] as Map<String, Any>
            val belowLayerIdArg = args[4] as String?
            api.addSymbolLayer(idArg, sourceIdArg, layoutArg, paintArg, belowLayerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.loadImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.loadImage(urlArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val bytesArg = args[1] as ByteArray
            api.addImage(idArg, bytesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addImages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idsArg = args[0] as List<String>
            val imagesArg = args[1] as List<ByteArray>
            api.addImages(idsArg, imagesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addSprite$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spriteJsonArg = args[0] as String
            val spriteImageArg = args[1] as ByteArray
            api.addSprite(spriteJsonArg, spriteImageArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addClusteredGeoJsonSource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val dataArg = args[1] as String
            val clusteredArg = args[2] as Boolean
            val clusterRadiusArg = args[3] as Double
            val clusterMaxZoomArg = args[4] as Double
            val clusterPropertiesJsonArg = args[5] as String?
            api.addClusteredGeoJsonSource(idArg, dataArg, clusteredArg, clusterRadiusArg, clusterMaxZoomArg, clusterPropertiesJsonArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addVectorSource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val tilesArg = args[1] as List<String>
            val minZoomArg = args[2] as Double
            val maxZoomArg = args[3] as Double
            api.addVectorSource(idArg, tilesArg, minZoomArg, maxZoomArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.testMethod$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as String
            api.testMethod(valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.animateCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val latitudeArg = args[0] as Double
            val longitudeArg = args[1] as Double
            val zoomArg = args[2] as Double
            val bearingArg = args[3] as Double
            val pitchArg = args[4] as Double
            val durationArg = args[5] as Long
            api.animateCamera(latitudeArg, longitudeArg, zoomArg, bearingArg, pitchArg, durationArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.getCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCamera())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.getZoomLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getZoomLevel())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.getUserLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getUserLocation())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.moveCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val latArg = args[0] as Double
            val lngArg = args[1] as Double
            val zoomArg = args[2] as Double
            val bearingArg = args[3] as Double
            val pitchArg = args[4] as Double
            api.moveCamera(latArg, lngArg, zoomArg, bearingArg, pitchArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.updateMapOptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val minZoomArg = args[0] as Double
            val maxZoomArg = args[1] as Double
            val minPitchArg = args[2] as Double
            val maxPitchArg = args[3] as Double
            val boundsWestArg = args[4] as Double
            val boundsSouthArg = args[5] as Double
            val boundsEastArg = args[6] as Double
            val boundsNorthArg = args[7] as Double
            val rotateEnabledArg = args[8] as Boolean
            val panEnabledArg = args[9] as Boolean
            val zoomEnabledArg = args[10] as Boolean
            val pitchEnabledArg = args[11] as Boolean
            api.updateMapOptions(minZoomArg, maxZoomArg, minPitchArg, maxPitchArg, boundsWestArg, boundsSouthArg, boundsEastArg, boundsNorthArg, rotateEnabledArg, panEnabledArg, zoomEnabledArg, pitchEnabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.enableLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fastestIntervalArg = args[0] as Long
            val maxWaitTimeArg = args[1] as Long
            val pulseFadeArg = args[2] as Boolean
            val accuracyAnimationArg = args[3] as Boolean
            val compassAnimationArg = args[4] as Boolean
            val pulseArg = args[5] as Boolean
            api.enableLocation(fastestIntervalArg, maxWaitTimeArg, pulseFadeArg, accuracyAnimationArg, compassAnimationArg, pulseArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.fitBounds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val westArg = args[0] as Double
            val southArg = args[1] as Double
            val eastArg = args[2] as Double
            val northArg = args[3] as Double
            val bearingArg = args[4] as Double
            val pitchArg = args[5] as Double
            val durationArg = args[6] as Long
            val paddingLeftArg = args[7] as Double
            val paddingTopArg = args[8] as Double
            val paddingRightArg = args[9] as Double
            val paddingBottomArg = args[10] as Double
            api.fitBounds(westArg, southArg, eastArg, northArg, bearingArg, pitchArg, durationArg, paddingLeftArg, paddingTopArg, paddingRightArg, paddingBottomArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.setContentInset$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val leftArg = args[0] as Double
            val topArg = args[1] as Double
            val rightArg = args[2] as Double
            val bottomArg = args[3] as Double
            api.setContentInset(leftArg, topArg, rightArg, bottomArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.getMetersPerPixelAtLatitude$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val latitudeArg = args[0] as Double
            api.getMetersPerPixelAtLatitude(latitudeArg) { result: Result<Double> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.getVisibleRegion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getVisibleRegion{ result: Result<List<Double>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.toLngLat$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val xArg = args[0] as Double
            val yArg = args[1] as Double
            api.toLngLat(xArg, yArg) { result: Result<List<Double>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.toScreenLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val lngArg = args[0] as Double
            val latArg = args[1] as Double
            api.toScreenLocation(lngArg, latArg) { result: Result<List<Double>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.queryLayers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val xArg = args[0] as Double
            val yArg = args[1] as Double
            api.queryLayers(xArg, yArg) { result: Result<List<Map<String, String>>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.queryLayersInRect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val leftArg = args[0] as Double
            val topArg = args[1] as Double
            val rightArg = args[2] as Double
            val bottomArg = args[3] as Double
            api.queryLayersInRect(leftArg, topArg, rightArg, bottomArg) { result: Result<List<Map<Any?, Any?>>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.trackLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val trackArg = args[0] as Boolean
            val bearingModeArg = args[1] as Long
            api.trackLocation(trackArg, bearingModeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.showUserLocationPuck$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val showArg = args[0] as Boolean
            api.showUserLocationPuck(showArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.removeLayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.removeLayer(idArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.removeSource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.removeSource(idArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.updateGeoJsonSource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val dataArg = args[1] as String
            api.updateGeoJsonSource(idArg, dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.setStyleUri$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val styleUriArg = args[0] as String
            api.setStyleUri(styleUriArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class MapLibreFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by MapLibreFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
  }
  /** Get the map options from dart. */
  fun getOptions(callback: (Result<MapOptions>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.getOptions$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as MapOptions
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Callback for when the style has been loaded. */
  fun onStyleLoaded(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onStyleLoaded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Callback for when the map is ready and can be used. */
  fun onMapReady(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onMapReady$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Callback when the user clicks on the map. */
  fun onClick(pointArg: LngLat, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onClick$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(pointArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Callback when the map idles. */
  fun onIdle(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onIdle$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Callback when the map camera idles. */
  fun onCameraIdle(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onCameraIdle$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Callback when the user performs a secondary click on the map
   * (e.g. by default a click with the right mouse button).
   */
  fun onSecondaryClick(pointArg: LngLat, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onSecondaryClick$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(pointArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Callback when the user performs a double click on the map. */
  fun onDoubleClick(pointArg: LngLat, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onDoubleClick$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(pointArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Callback when the user performs a long lasting click on the map. */
  fun onLongClick(pointArg: LngLat, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onLongClick$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(pointArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Callback when the map camera changes. */
  fun onMoveCamera(cameraArg: MapCamera, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onMoveCamera$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(cameraArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Callback when the map camera starts changing. */
  fun onStartMoveCamera(reasonArg: CameraChangeReason, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onStartMoveCamera$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(reasonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PermissionManagerHostApi {
  /** Request location permissions. */
  fun requestLocationPermissions(explanation: String, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by PermissionManagerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `PermissionManagerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PermissionManagerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.PermissionManagerHostApi.requestLocationPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val explanationArg = args[0] as String
            api.requestLocationPermissions(explanationArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface OfflineManagerHostApi {
  /** Clear the ambient cache. */
  fun clearAmbientCache(callback: (Result<Unit>) -> Unit)
  /** Invalidate the ambient cache. */
  fun invalidateAmbientCache(callback: (Result<Unit>) -> Unit)
  /** Reset database. */
  fun resetDatabase(callback: (Result<Unit>) -> Unit)
  /** Set maximum ambient cache size. */
  fun setMaximumAmbientCacheSize(bytes: Long, callback: (Result<Unit>) -> Unit)
  /** Download a map region. */
  fun downloadRegion(mapStyleUrl: String, bounds: LngLatBounds, minZoom: Double, maxZoom: Double, pixelDensity: Double, metadata: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by OfflineManagerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `OfflineManagerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OfflineManagerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.OfflineManagerHostApi.clearAmbientCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearAmbientCache{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.OfflineManagerHostApi.invalidateAmbientCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.invalidateAmbientCache{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.OfflineManagerHostApi.resetDatabase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.resetDatabase{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.OfflineManagerHostApi.setMaximumAmbientCacheSize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val bytesArg = args[0] as Long
            api.setMaximumAmbientCacheSize(bytesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapmetrics.OfflineManagerHostApi.downloadRegion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mapStyleUrlArg = args[0] as String
            val boundsArg = args[1] as LngLatBounds
            val minZoomArg = args[2] as Double
            val maxZoomArg = args[3] as Double
            val pixelDensityArg = args[4] as Double
            val metadataArg = args[5] as String
            api.downloadRegion(mapStyleUrlArg, boundsArg, minZoomArg, maxZoomArg, pixelDensityArg, metadataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
