// swiftformat:disable all
// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Influences the y direction of the tile coordinates.
enum TileScheme: Int {
  /// Slippy map tilenames scheme.
  case xyz = 0
  /// OSGeo spec scheme.
  case tms = 1
}

/// The encoding used by this source. Mapbox Terrain RGB is used by default.
enum RasterDemEncoding: Int {
  /// Terrarium format PNG tiles.
  case terrarium = 0
  /// Mapbox Terrain RGB tiles.
  case mapbox = 1
  /// Decodes tiles using the redFactor, blueFactor, greenFactor, baseShift
  /// parameters.
  case custom = 2
}

/// The reason the camera is changing.
enum CameraChangeReason: Int {
  /// Developer animation.
  case developerAnimation = 0
  /// API animation.
  case apiAnimation = 1
  /// API gesture
  case apiGesture = 2
}

/// A longitude/latitude coordinate object.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LngLat {
  /// The longitude
  var lng: Double
  /// The latitude
  var lat: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LngLat? {
    let lng = pigeonVar_list[0] as! Double
    let lat = pigeonVar_list[1] as! Double

    return LngLat(
      lng: lng,
      lat: lat
    )
  }
  func toList() -> [Any?] {
    return [
      lng,
      lat,
    ]
  }
}

/// The map options define initial values for the MapLibre map.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MapOptions {
  /// The URL of the used map style.
  var style: String
  /// The initial zoom level of the map.
  var zoom: Double
  /// The initial pitch / tilt of the map.
  var pitch: Double
  /// The initial bearing of the map.
  var bearing: Double
  /// The initial center coordinates of the map.
  var center: LngLat? = nil
  /// The maximum bounding box of the map camera.
  var maxBounds: LngLatBounds? = nil
  /// The minimum zoom level of the map.
  var minZoom: Double
  /// The maximum zoom level of the map.
  var maxZoom: Double
  /// The minimum pitch / tilt of the map.
  var minPitch: Double
  /// The maximum pitch / tilt of the map.
  var maxPitch: Double
  /// The map gestures.
  var gestures: MapGestures
  /// Toggle the texture mode on android.
  var androidTextureMode: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MapOptions? {
    let style = pigeonVar_list[0] as! String
    let zoom = pigeonVar_list[1] as! Double
    let pitch = pigeonVar_list[2] as! Double
    let bearing = pigeonVar_list[3] as! Double
    let center: LngLat? = nilOrValue(pigeonVar_list[4])
    let maxBounds: LngLatBounds? = nilOrValue(pigeonVar_list[5])
    let minZoom = pigeonVar_list[6] as! Double
    let maxZoom = pigeonVar_list[7] as! Double
    let minPitch = pigeonVar_list[8] as! Double
    let maxPitch = pigeonVar_list[9] as! Double
    let gestures = pigeonVar_list[10] as! MapGestures
    let androidTextureMode = pigeonVar_list[11] as! Bool

    return MapOptions(
      style: style,
      zoom: zoom,
      pitch: pitch,
      bearing: bearing,
      center: center,
      maxBounds: maxBounds,
      minZoom: minZoom,
      maxZoom: maxZoom,
      minPitch: minPitch,
      maxPitch: maxPitch,
      gestures: gestures,
      androidTextureMode: androidTextureMode
    )
  }
  func toList() -> [Any?] {
    return [
      style,
      zoom,
      pitch,
      bearing,
      center,
      maxBounds,
      minZoom,
      maxZoom,
      minPitch,
      maxPitch,
      gestures,
      androidTextureMode,
    ]
  }
}

/// Map gestures
///
/// Generated class from Pigeon that represents data sent in messages.
struct MapGestures {
  /// Rotate the map bearing.
  var rotate: Bool
  /// Move the center of the map around.
  var pan: Bool
  /// Zoom the map in and out.
  var zoom: Bool
  /// Tilt (pitch) the map camera.
  var tilt: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MapGestures? {
    let rotate = pigeonVar_list[0] as! Bool
    let pan = pigeonVar_list[1] as! Bool
    let zoom = pigeonVar_list[2] as! Bool
    let tilt = pigeonVar_list[3] as! Bool

    return MapGestures(
      rotate: rotate,
      pan: pan,
      zoom: zoom,
      tilt: tilt
    )
  }
  func toList() -> [Any?] {
    return [
      rotate,
      pan,
      zoom,
      tilt,
    ]
  }
}

/// A pixel location / location on the device screen.
///
/// Generated class from Pigeon that represents data sent in messages.
struct Offset {
  /// The x coordinate
  var x: Double
  /// The y coordinate
  var y: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Offset? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double

    return Offset(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
}

/// Camera Padding
///
/// Generated class from Pigeon that represents data sent in messages.
struct Padding {
  var top: Int64
  var bottom: Int64
  var left: Int64
  var right: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Padding? {
    let top = pigeonVar_list[0] as! Int64
    let bottom = pigeonVar_list[1] as! Int64
    let left = pigeonVar_list[2] as! Int64
    let right = pigeonVar_list[3] as! Int64

    return Padding(
      top: top,
      bottom: bottom,
      left: left,
      right: right
    )
  }
  func toList() -> [Any?] {
    return [
      top,
      bottom,
      left,
      right,
    ]
  }
}

/// The current position of the map camera.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MapCamera {
  var center: LngLat
  var zoom: Double
  var pitch: Double
  var bearing: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MapCamera? {
    let center = pigeonVar_list[0] as! LngLat
    let zoom = pigeonVar_list[1] as! Double
    let pitch = pigeonVar_list[2] as! Double
    let bearing = pigeonVar_list[3] as! Double

    return MapCamera(
      center: center,
      zoom: zoom,
      pitch: pitch,
      bearing: bearing
    )
  }
  func toList() -> [Any?] {
    return [
      center,
      zoom,
      pitch,
      bearing,
    ]
  }
}

/// LatLng bound object
///
/// Generated class from Pigeon that represents data sent in messages.
struct LngLatBounds {
  var longitudeWest: Double
  var longitudeEast: Double
  var latitudeSouth: Double
  var latitudeNorth: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LngLatBounds? {
    let longitudeWest = pigeonVar_list[0] as! Double
    let longitudeEast = pigeonVar_list[1] as! Double
    let latitudeSouth = pigeonVar_list[2] as! Double
    let latitudeNorth = pigeonVar_list[3] as! Double

    return LngLatBounds(
      longitudeWest: longitudeWest,
      longitudeEast: longitudeEast,
      latitudeSouth: latitudeSouth,
      latitudeNorth: latitudeNorth
    )
  }
  func toList() -> [Any?] {
    return [
      longitudeWest,
      longitudeEast,
      latitudeSouth,
      latitudeNorth,
    ]
  }
}

/// Model that describes an offline map region.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OfflineRegion {
  var id: Int64
  var bounds: LngLatBounds
  var minZoom: Double
  var maxZoom: Double
  var pixelRatio: Double
  var styleUrl: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OfflineRegion? {
    let id = pigeonVar_list[0] as! Int64
    let bounds = pigeonVar_list[1] as! LngLatBounds
    let minZoom = pigeonVar_list[2] as! Double
    let maxZoom = pigeonVar_list[3] as! Double
    let pixelRatio = pigeonVar_list[4] as! Double
    let styleUrl = pigeonVar_list[5] as! String

    return OfflineRegion(
      id: id,
      bounds: bounds,
      minZoom: minZoom,
      maxZoom: maxZoom,
      pixelRatio: pixelRatio,
      styleUrl: styleUrl
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      bounds,
      minZoom,
      maxZoom,
      pixelRatio,
      styleUrl,
    ]
  }
}

private class PigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TileScheme(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RasterDemEncoding(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraChangeReason(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return LngLat.fromList(self.readValue() as! [Any?])
    case 133:
      return MapOptions.fromList(self.readValue() as! [Any?])
    case 134:
      return MapGestures.fromList(self.readValue() as! [Any?])
    case 135:
      return Offset.fromList(self.readValue() as! [Any?])
    case 136:
      return Padding.fromList(self.readValue() as! [Any?])
    case 137:
      return MapCamera.fromList(self.readValue() as! [Any?])
    case 138:
      return LngLatBounds.fromList(self.readValue() as! [Any?])
    case 139:
      return OfflineRegion.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TileScheme {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? RasterDemEncoding {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraChangeReason {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? LngLat {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? MapOptions {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? MapGestures {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? Offset {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? Padding {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? MapCamera {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? LngLatBounds {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? OfflineRegion {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonPigeonCodecWriter(data: data)
  }
}

class PigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonPigeonCodec(readerWriter: PigeonPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MapLibreHostApi {
  func dispose() throws
  /// Add a fill layer to the map style.
  func addFillLayer(id: String, sourceId: String, layout: [String: Any], paint: [String: Any], belowLayerId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Add a circle layer to the map style.
  func addCircleLayer(id: String, sourceId: String, layout: [String: Any], paint: [String: Any], belowLayerId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Add a background layer to the map style.
  func addBackgroundLayer(id: String, layout: [String: Any], paint: [String: Any], belowLayerId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Add a fill extrusion layer to the map style.
  func addFillExtrusionLayer(id: String, sourceId: String, layout: [String: Any], paint: [String: Any], belowLayerId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Add a heatmap layer to the map style.
  func addHeatmapLayer(id: String, sourceId: String, layout: [String: Any], paint: [String: Any], belowLayerId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Add a hillshade layer to the map style.
  func addHillshadeLayer(id: String, sourceId: String, layout: [String: Any], paint: [String: Any], belowLayerId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Add a line layer to the map style.
  func addLineLayer(id: String, sourceId: String, layout: [String: Any], paint: [String: Any], belowLayerId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Add a raster layer to the map style.
  func addRasterLayer(id: String, sourceId: String, layout: [String: Any], paint: [String: Any], belowLayerId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Add a symbol layer to the map style.
  func addSymbolLayer(id: String, sourceId: String, layout: [String: Any], paint: [String: Any], belowLayerId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Loads an image to the map. An image needs to be loaded before it can
  /// get used.
  func loadImage(url: String, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Add an image to the map.
  func addImage(id: String, bytes: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  /// Add a GeoJSON source with clustering to the map style.
  func addClusteredGeoJsonSource(id: String, data: String, clustered: Bool, clusterRadius: Double, clusterMaxZoom: Double, completion: @escaping (Result<Void, Error>) -> Void)
  /// Minimal test method to debug Pigeon generation.
  func testMethod(value: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Animate the camera to a new position.
  /// Use -1.0 or double.nan for any value you do not want to change.
  func animateCamera(latitude: Double, longitude: Double, zoom: Double, bearing: Double, pitch: Double, duration: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  /// Get the current camera state.
  func getCamera() throws -> MapCamera
  /// Get the current zoom level.
  func getZoomLevel() throws -> Double
  /// Get the user's current location.
  func getUserLocation() throws -> LngLat
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MapLibreHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `MapLibreHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MapLibreHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    /// Add a fill layer to the map style.
    let addFillLayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addFillLayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addFillLayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let sourceIdArg = args[1] as! String
        let layoutArg = args[2] as! [String: Any]
        let paintArg = args[3] as! [String: Any]
        let belowLayerIdArg: String? = nilOrValue(args[4])
        api.addFillLayer(id: idArg, sourceId: sourceIdArg, layout: layoutArg, paint: paintArg, belowLayerId: belowLayerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addFillLayerChannel.setMessageHandler(nil)
    }
    /// Add a circle layer to the map style.
    let addCircleLayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addCircleLayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addCircleLayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let sourceIdArg = args[1] as! String
        let layoutArg = args[2] as! [String: Any]
        let paintArg = args[3] as! [String: Any]
        let belowLayerIdArg: String? = nilOrValue(args[4])
        api.addCircleLayer(id: idArg, sourceId: sourceIdArg, layout: layoutArg, paint: paintArg, belowLayerId: belowLayerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addCircleLayerChannel.setMessageHandler(nil)
    }
    /// Add a background layer to the map style.
    let addBackgroundLayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addBackgroundLayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addBackgroundLayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let layoutArg = args[1] as! [String: Any]
        let paintArg = args[2] as! [String: Any]
        let belowLayerIdArg: String? = nilOrValue(args[3])
        api.addBackgroundLayer(id: idArg, layout: layoutArg, paint: paintArg, belowLayerId: belowLayerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addBackgroundLayerChannel.setMessageHandler(nil)
    }
    /// Add a fill extrusion layer to the map style.
    let addFillExtrusionLayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addFillExtrusionLayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addFillExtrusionLayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let sourceIdArg = args[1] as! String
        let layoutArg = args[2] as! [String: Any]
        let paintArg = args[3] as! [String: Any]
        let belowLayerIdArg: String? = nilOrValue(args[4])
        api.addFillExtrusionLayer(id: idArg, sourceId: sourceIdArg, layout: layoutArg, paint: paintArg, belowLayerId: belowLayerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addFillExtrusionLayerChannel.setMessageHandler(nil)
    }
    /// Add a heatmap layer to the map style.
    let addHeatmapLayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addHeatmapLayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addHeatmapLayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let sourceIdArg = args[1] as! String
        let layoutArg = args[2] as! [String: Any]
        let paintArg = args[3] as! [String: Any]
        let belowLayerIdArg: String? = nilOrValue(args[4])
        api.addHeatmapLayer(id: idArg, sourceId: sourceIdArg, layout: layoutArg, paint: paintArg, belowLayerId: belowLayerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addHeatmapLayerChannel.setMessageHandler(nil)
    }
    /// Add a hillshade layer to the map style.
    let addHillshadeLayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addHillshadeLayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addHillshadeLayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let sourceIdArg = args[1] as! String
        let layoutArg = args[2] as! [String: Any]
        let paintArg = args[3] as! [String: Any]
        let belowLayerIdArg: String? = nilOrValue(args[4])
        api.addHillshadeLayer(id: idArg, sourceId: sourceIdArg, layout: layoutArg, paint: paintArg, belowLayerId: belowLayerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addHillshadeLayerChannel.setMessageHandler(nil)
    }
    /// Add a line layer to the map style.
    let addLineLayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addLineLayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addLineLayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let sourceIdArg = args[1] as! String
        let layoutArg = args[2] as! [String: Any]
        let paintArg = args[3] as! [String: Any]
        let belowLayerIdArg: String? = nilOrValue(args[4])
        api.addLineLayer(id: idArg, sourceId: sourceIdArg, layout: layoutArg, paint: paintArg, belowLayerId: belowLayerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addLineLayerChannel.setMessageHandler(nil)
    }
    /// Add a raster layer to the map style.
    let addRasterLayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addRasterLayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addRasterLayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let sourceIdArg = args[1] as! String
        let layoutArg = args[2] as! [String: Any]
        let paintArg = args[3] as! [String: Any]
        let belowLayerIdArg: String? = nilOrValue(args[4])
        api.addRasterLayer(id: idArg, sourceId: sourceIdArg, layout: layoutArg, paint: paintArg, belowLayerId: belowLayerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addRasterLayerChannel.setMessageHandler(nil)
    }
    /// Add a symbol layer to the map style.
    let addSymbolLayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addSymbolLayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addSymbolLayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let sourceIdArg = args[1] as! String
        let layoutArg = args[2] as! [String: Any]
        let paintArg = args[3] as! [String: Any]
        let belowLayerIdArg: String? = nilOrValue(args[4])
        api.addSymbolLayer(id: idArg, sourceId: sourceIdArg, layout: layoutArg, paint: paintArg, belowLayerId: belowLayerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addSymbolLayerChannel.setMessageHandler(nil)
    }
    /// Loads an image to the map. An image needs to be loaded before it can
    /// get used.
    let loadImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.loadImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.loadImage(url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadImageChannel.setMessageHandler(nil)
    }
    /// Add an image to the map.
    let addImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let bytesArg = args[1] as! FlutterStandardTypedData
        api.addImage(id: idArg, bytes: bytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addImageChannel.setMessageHandler(nil)
    }
    /// Add a GeoJSON source with clustering to the map style.
    let addClusteredGeoJsonSourceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.addClusteredGeoJsonSource\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addClusteredGeoJsonSourceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let dataArg = args[1] as! String
        let clusteredArg = args[2] as! Bool
        let clusterRadiusArg = args[3] as! Double
        let clusterMaxZoomArg = args[4] as! Double
        api.addClusteredGeoJsonSource(id: idArg, data: dataArg, clustered: clusteredArg, clusterRadius: clusterRadiusArg, clusterMaxZoom: clusterMaxZoomArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addClusteredGeoJsonSourceChannel.setMessageHandler(nil)
    }
    /// Minimal test method to debug Pigeon generation.
    let testMethodChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.testMethod\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      testMethodChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! String
        api.testMethod(value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      testMethodChannel.setMessageHandler(nil)
    }
    /// Animate the camera to a new position.
    /// Use -1.0 or double.nan for any value you do not want to change.
    let animateCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.animateCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      animateCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let latitudeArg = args[0] as! Double
        let longitudeArg = args[1] as! Double
        let zoomArg = args[2] as! Double
        let bearingArg = args[3] as! Double
        let pitchArg = args[4] as! Double
        let durationArg = args[5] as! Int64
        api.animateCamera(latitude: latitudeArg, longitude: longitudeArg, zoom: zoomArg, bearing: bearingArg, pitch: pitchArg, duration: durationArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      animateCameraChannel.setMessageHandler(nil)
    }
    /// Get the current camera state.
    let getCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.getCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCameraChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCamera()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCameraChannel.setMessageHandler(nil)
    }
    /// Get the current zoom level.
    let getZoomLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.getZoomLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getZoomLevelChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getZoomLevel()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getZoomLevelChannel.setMessageHandler(nil)
    }
    /// Get the user's current location.
    let getUserLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.MapLibreHostApi.getUserLocation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUserLocationChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getUserLocation()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getUserLocationChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MapLibreFlutterApiProtocol {
  /// Get the map options from dart.
  func getOptions(completion: @escaping (Result<MapOptions, PigeonError>) -> Void)
  /// Callback for when the style has been loaded.
  func onStyleLoaded(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Callback for when the map is ready and can be used.
  func onMapReady(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Callback when the user clicks on the map.
  func onClick(point pointArg: LngLat, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Callback when the map idles.
  func onIdle(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Callback when the map camera idles.
  func onCameraIdle(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Callback when the user performs a secondary click on the map
  /// (e.g. by default a click with the right mouse button).
  func onSecondaryClick(point pointArg: LngLat, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Callback when the user performs a double click on the map.
  func onDoubleClick(point pointArg: LngLat, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Callback when the user performs a long lasting click on the map.
  func onLongClick(point pointArg: LngLat, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Callback when the map camera changes.
  func onMoveCamera(camera cameraArg: MapCamera, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Callback when the map camera starts changing.
  func onStartMoveCamera(reason reasonArg: CameraChangeReason, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class MapLibreFlutterApi: MapLibreFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonPigeonCodec {
    return PigeonPigeonCodec.shared
  }
  /// Get the map options from dart.
  func getOptions(completion: @escaping (Result<MapOptions, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.getOptions\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! MapOptions
        completion(.success(result))
      }
    }
  }
  /// Callback for when the style has been loaded.
  func onStyleLoaded(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onStyleLoaded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Callback for when the map is ready and can be used.
  func onMapReady(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onMapReady\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Callback when the user clicks on the map.
  func onClick(point pointArg: LngLat, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onClick\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([pointArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Callback when the map idles.
  func onIdle(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onIdle\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Callback when the map camera idles.
  func onCameraIdle(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onCameraIdle\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Callback when the user performs a secondary click on the map
  /// (e.g. by default a click with the right mouse button).
  func onSecondaryClick(point pointArg: LngLat, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onSecondaryClick\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([pointArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Callback when the user performs a double click on the map.
  func onDoubleClick(point pointArg: LngLat, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onDoubleClick\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([pointArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Callback when the user performs a long lasting click on the map.
  func onLongClick(point pointArg: LngLat, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onLongClick\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([pointArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Callback when the map camera changes.
  func onMoveCamera(camera cameraArg: MapCamera, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onMoveCamera\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([cameraArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Callback when the map camera starts changing.
  func onStartMoveCamera(reason reasonArg: CameraChangeReason, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.mapmetrics.MapLibreFlutterApi.onStartMoveCamera\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([reasonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PermissionManagerHostApi {
  /// Request location permissions.
  func requestLocationPermissions(explanation: String, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PermissionManagerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `PermissionManagerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PermissionManagerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Request location permissions.
    let requestLocationPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.PermissionManagerHostApi.requestLocationPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestLocationPermissionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let explanationArg = args[0] as! String
        api.requestLocationPermissions(explanation: explanationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestLocationPermissionsChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OfflineManagerHostApi {
  /// Clear the ambient cache.
  func clearAmbientCache(completion: @escaping (Result<Void, Error>) -> Void)
  /// Invalidate the ambient cache.
  func invalidateAmbientCache(completion: @escaping (Result<Void, Error>) -> Void)
  /// Reset database.
  func resetDatabase(completion: @escaping (Result<Void, Error>) -> Void)
  /// Set maximum ambient cache size.
  func setMaximumAmbientCacheSize(bytes: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  /// Download a map region.
  func downloadRegion(mapStyleUrl: String, bounds: LngLatBounds, minZoom: Double, maxZoom: Double, pixelDensity: Double, metadata: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OfflineManagerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `OfflineManagerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OfflineManagerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Clear the ambient cache.
    let clearAmbientCacheChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.OfflineManagerHostApi.clearAmbientCache\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearAmbientCacheChannel.setMessageHandler { _, reply in
        api.clearAmbientCache { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearAmbientCacheChannel.setMessageHandler(nil)
    }
    /// Invalidate the ambient cache.
    let invalidateAmbientCacheChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.OfflineManagerHostApi.invalidateAmbientCache\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      invalidateAmbientCacheChannel.setMessageHandler { _, reply in
        api.invalidateAmbientCache { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      invalidateAmbientCacheChannel.setMessageHandler(nil)
    }
    /// Reset database.
    let resetDatabaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.OfflineManagerHostApi.resetDatabase\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetDatabaseChannel.setMessageHandler { _, reply in
        api.resetDatabase { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resetDatabaseChannel.setMessageHandler(nil)
    }
    /// Set maximum ambient cache size.
    let setMaximumAmbientCacheSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.OfflineManagerHostApi.setMaximumAmbientCacheSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMaximumAmbientCacheSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let bytesArg = args[0] as! Int64
        api.setMaximumAmbientCacheSize(bytes: bytesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setMaximumAmbientCacheSizeChannel.setMessageHandler(nil)
    }
    /// Download a map region.
    let downloadRegionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mapmetrics.OfflineManagerHostApi.downloadRegion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadRegionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mapStyleUrlArg = args[0] as! String
        let boundsArg = args[1] as! LngLatBounds
        let minZoomArg = args[2] as! Double
        let maxZoomArg = args[3] as! Double
        let pixelDensityArg = args[4] as! Double
        let metadataArg = args[5] as! String
        api.downloadRegion(mapStyleUrl: mapStyleUrlArg, bounds: boundsArg, minZoom: minZoomArg, maxZoom: maxZoomArg, pixelDensity: pixelDensityArg, metadata: metadataArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      downloadRegionChannel.setMessageHandler(nil)
    }
  }
}
