// ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field, return_of_invalid_type, void_checks, annotate_overrides, no_leading_underscores_for_local_identifiers, library_private_types_in_public_api
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;
import 'dart:io' show Platform;

// FFI function declarations for clustering
typedef _createShapeSourceWithClustering_C =
    ffi.Pointer<ffi.Void> Function(
      ffi.Pointer<ffi.Int8> identifier,
      ffi.Pointer<ffi.Int8> shape,
      ffi.Pointer<ffi.Int8> options,
    );

typedef _createShapeSourceWithClustering_Dart =
    ffi.Pointer<ffi.Void> Function(
      ffi.Pointer<ffi.Int8> identifier,
      ffi.Pointer<ffi.Int8> shape,
      ffi.Pointer<ffi.Int8> options,
    );

// Stub classes for MapLibre types
class MLNMapView {
  final ffi.Pointer<ffi.Void> _pointer;

  MLNMapView(this._pointer);

  static MLNMapView castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNMapView(pointer);
  }

  // Stub properties and methods
  double get zoomLevel => 0.0;
  set zoomLevel(double value) {}

  MLNMapCamera get camera => MLNMapCamera(ffi.nullptr);
  set camera(MLNMapCamera value) {}

  bool get showsUserLocation => false;
  set showsUserLocation(bool value) {}

  MLNStyle? get style => null;

  void flyToCamera_withDuration_completionHandler_(
    MLNMapCamera camera,
    double duration,
    ffi.Pointer<ffi.Void>? completion,
  ) {}
  void setCamera_animated_(MLNMapCamera camera, bool animated) {}
  void setVisibleCoordinateBounds_animated_(
    MLNCoordinateBounds bounds,
    bool animated,
  ) {}

  double get minimumZoomLevel => 0.0;
  set minimumZoomLevel(double value) {}

  double get maximumZoomLevel => 0.0;
  set maximumZoomLevel(double value) {}

  double get minimumPitch => 0.0;
  set minimumPitch(double value) {}

  double get maximumPitch => 0.0;
  set maximumPitch(double value) {}

  // Additional properties needed
  bool get rotateEnabled => false;
  set rotateEnabled(bool value) {}

  bool get scrollEnabled => false;
  set scrollEnabled(bool value) {}

  bool get zoomEnabled => false;
  set zoomEnabled(bool value) {}

  bool get pitchEnabled => false;
  set pitchEnabled(bool value) {}

  MLNCoordinateBounds get visibleCoordinateBounds =>
      throw UnimplementedError('FFI not implemented');

  double metersPerPointAtLatitude_(double latitude) => 0.0;

  MLNCoordinateBounds? get maximumScreenBounds => null;
  set maximumScreenBounds(MLNCoordinateBounds? value) {}

  int get userTrackingMode => 0;
  set userTrackingMode(int value) {}
}

class MLNMapCamera {
  final ffi.Pointer<ffi.Void> _pointer;

  MLNMapCamera(this._pointer);

  static MLNMapCamera castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNMapCamera(pointer);
  }

  // Stub properties
  double get pitch => 0.0;
  set pitch(double value) {}

  double get heading => 0.0;
  set heading(double value) {}
}

class MLNMapProjection {
  final ffi.Pointer<ffi.Void> _pointer;

  MLNMapProjection(this._pointer);

  static MLNMapProjection castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNMapProjection(pointer);
  }
}

class MLNStyle {
  final ffi.Pointer<ffi.Void> _pointer;

  MLNStyle(this._pointer);

  static MLNStyle castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNStyle(pointer);
  }

  dynamic sourceWithIdentifier_(dynamic identifier) {
    // TODO: Implement proper FFI call
    return null;
  }

  void addLayer_(dynamic layer) {
    // TODO: Implement proper FFI call
  }

  void addSource_(dynamic source) {
    // TODO: Implement proper FFI call
  }

  void removeImageForName_(dynamic name) {
    // TODO: Implement proper FFI call
  }

  dynamic layerWithIdentifier_(dynamic identifier) {
    // TODO: Implement proper FFI call
    return null;
  }

  void removeLayer_(dynamic layer) {
    // TODO: Implement proper FFI call
  }

  void removeSource_(dynamic source) {
    // TODO: Implement proper FFI call
  }

  dynamic get layers {
    // TODO: Implement proper FFI call
    return null;
  }

  dynamic get sources {
    // TODO: Implement proper FFI call
    return null;
  }
}

class MLNSource {
  final ffi.Pointer<ffi.Void> _pointer;

  MLNSource(this._pointer);

  static MLNSource castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNSource(pointer);
  }
}

class MLNVectorTileSource extends MLNSource {
  MLNVectorTileSource(super._pointer);

  static MLNVectorTileSource castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNVectorTileSource(pointer);
  }

  static MLNVectorTileSource new1() {
    // TODO: Implement proper FFI call
    return MLNVectorTileSource(ffi.nullptr);
  }

  void initWithIdentifier_configurationURLString_(
    dynamic identifier,
    dynamic configurationURLString,
  ) {
    // TODO: Implement proper FFI call
  }

  void initWithIdentifier_tileURLTemplates_options_(
    dynamic identifier,
    dynamic tileURLTemplates,
    dynamic options,
  ) {
    // TODO: Implement proper FFI call
  }
}

class MLNImageSource extends MLNSource {
  MLNImageSource(super._pointer);

  static MLNImageSource castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNImageSource(pointer);
  }

  static MLNImageSource new1() {
    // TODO: Implement proper FFI call
    return MLNImageSource(ffi.nullptr);
  }

  void initWithIdentifier_coordinateQuad_URL_(
    dynamic identifier,
    dynamic coordinateQuad,
    dynamic url,
  ) {
    // TODO: Implement proper FFI call
  }
}

class MLNRasterTileSource extends MLNSource {
  MLNRasterTileSource(super._pointer);

  static MLNRasterTileSource castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNRasterTileSource(pointer);
  }

  static MLNRasterTileSource new1() {
    // TODO: Implement proper FFI call
    return MLNRasterTileSource(ffi.nullptr);
  }

  void initWithIdentifier_configurationURL_tileSize_(
    dynamic identifier,
    dynamic configurationURL,
    dynamic tileSize,
  ) {
    // TODO: Implement proper FFI call
  }

  void initWithIdentifier_tileURLTemplates_options_(
    dynamic identifier,
    dynamic tileURLTemplates,
    dynamic options,
  ) {
    // TODO: Implement proper FFI call
  }
}

class MLNRasterDEMSource extends MLNSource {
  MLNRasterDEMSource(super._pointer);

  static MLNRasterDEMSource castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNRasterDEMSource(pointer);
  }

  static MLNRasterDEMSource new1() {
    // TODO: Implement proper FFI call
    return MLNRasterDEMSource(ffi.nullptr);
  }

  void initWithIdentifier_configurationURL_tileSize_(
    dynamic identifier,
    dynamic configurationURL,
    dynamic tileSize,
  ) {
    // TODO: Implement proper FFI call
  }

  void initWithIdentifier_tileURLTemplates_options_(
    dynamic identifier,
    dynamic tileURLTemplates,
    dynamic options,
  ) {
    // TODO: Implement proper FFI call
  }
}

class MLNStyleLayer {
  final ffi.Pointer<ffi.Void> _pointer;

  MLNStyleLayer(this._pointer);

  static MLNStyleLayer castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNStyleLayer(pointer);
  }

  static MLNStyleLayer new1() {
    // TODO: Implement proper FFI call
    return MLNStyleLayer(ffi.nullptr);
  }

  void setProperties(dynamic properties) {
    // TODO: Implement proper FFI call
  }

  set minimumZoomLevel(dynamic value) {
    // TODO: Implement proper FFI call
  }

  set maximumZoomLevel(dynamic value) {
    // TODO: Implement proper FFI call
  }
}

class MLNBackgroundStyleLayer extends MLNStyleLayer {
  MLNBackgroundStyleLayer(super._pointer);

  static MLNBackgroundStyleLayer castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNBackgroundStyleLayer(pointer);
  }

  static MLNBackgroundStyleLayer new1() {
    // TODO: Implement proper FFI call
    return MLNBackgroundStyleLayer(ffi.nullptr);
  }

  void initWithIdentifier_(dynamic identifier) {
    // TODO: Implement proper FFI call
  }

  set backgroundColor(dynamic value) {
    // TODO: Implement proper FFI call
  }
}

class MLNCircleStyleLayer extends MLNStyleLayer {
  MLNCircleStyleLayer(super._pointer);

  static MLNCircleStyleLayer castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNCircleStyleLayer(pointer);
  }

  static MLNCircleStyleLayer new1() {
    // TODO: Implement proper FFI call
    return MLNCircleStyleLayer(ffi.nullptr);
  }

  void initWithIdentifier_source_(dynamic identifier, dynamic source) {
    // TODO: Implement proper FFI call
  }
}

class MLNFillExtrusionStyleLayer extends MLNStyleLayer {
  MLNFillExtrusionStyleLayer(super._pointer);

  static MLNFillExtrusionStyleLayer castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNFillExtrusionStyleLayer(pointer);
  }

  static MLNFillExtrusionStyleLayer new1() {
    // TODO: Implement proper FFI call
    return MLNFillExtrusionStyleLayer(ffi.nullptr);
  }

  void initWithIdentifier_source_(dynamic identifier, dynamic source) {
    // TODO: Implement proper FFI call
  }
}

class MLNFillStyleLayer extends MLNStyleLayer {
  MLNFillStyleLayer(super._pointer);

  static MLNFillStyleLayer castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNFillStyleLayer(pointer);
  }

  static MLNFillStyleLayer new1() {
    // TODO: Implement proper FFI call
    return MLNFillStyleLayer(ffi.nullptr);
  }

  void initWithIdentifier_source_(dynamic identifier, dynamic source) {
    // TODO: Implement proper FFI call
  }
}

class MLNHeatmapStyleLayer extends MLNStyleLayer {
  MLNHeatmapStyleLayer(super._pointer);

  static MLNHeatmapStyleLayer castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNHeatmapStyleLayer(pointer);
  }

  static MLNHeatmapStyleLayer new1() {
    // TODO: Implement proper FFI call
    return MLNHeatmapStyleLayer(ffi.nullptr);
  }

  void initWithIdentifier_source_(dynamic identifier, dynamic source) {
    // TODO: Implement proper FFI call
  }
}

class MLNHillshadeStyleLayer extends MLNStyleLayer {
  MLNHillshadeStyleLayer(super._pointer);

  static MLNHillshadeStyleLayer castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNHillshadeStyleLayer(pointer);
  }

  static MLNHillshadeStyleLayer new1() {
    // TODO: Implement proper FFI call
    return MLNHillshadeStyleLayer(ffi.nullptr);
  }

  void initWithIdentifier_source_(dynamic identifier, dynamic source) {
    // TODO: Implement proper FFI call
  }
}

class MLNLineStyleLayer extends MLNStyleLayer {
  MLNLineStyleLayer(super._pointer);

  static MLNLineStyleLayer castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNLineStyleLayer(pointer);
  }

  static MLNLineStyleLayer new1() {
    // TODO: Implement proper FFI call
    return MLNLineStyleLayer(ffi.nullptr);
  }

  void initWithIdentifier_source_(dynamic identifier, dynamic source) {
    // TODO: Implement proper FFI call
  }
}

class MLNRasterStyleLayer extends MLNStyleLayer {
  MLNRasterStyleLayer(super._pointer);

  static MLNRasterStyleLayer castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNRasterStyleLayer(pointer);
  }

  static MLNRasterStyleLayer new1() {
    // TODO: Implement proper FFI call
    return MLNRasterStyleLayer(ffi.nullptr);
  }

  void initWithIdentifier_source_(dynamic identifier, dynamic source) {
    // TODO: Implement proper FFI call
  }
}

class MLNSymbolStyleLayer extends MLNStyleLayer {
  MLNSymbolStyleLayer(super._pointer);

  static MLNSymbolStyleLayer castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNSymbolStyleLayer(pointer);
  }

  static MLNSymbolStyleLayer new1() {
    // TODO: Implement proper FFI call
    return MLNSymbolStyleLayer(ffi.nullptr);
  }

  void initWithIdentifier_source_(dynamic identifier, dynamic source) {
    // TODO: Implement proper FFI call
  }
}

class MLNVectorStyleLayer extends MLNStyleLayer {
  MLNVectorStyleLayer(super._pointer);

  static MLNVectorStyleLayer castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNVectorStyleLayer(pointer);
  }

  static MLNVectorStyleLayer new1() {
    // TODO: Implement proper FFI call
    return MLNVectorStyleLayer(ffi.nullptr);
  }
}

class MLNAttributionInfo {
  final ffi.Pointer<ffi.Void> _pointer;

  MLNAttributionInfo(this._pointer);

  static MLNAttributionInfo castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNAttributionInfo(pointer);
  }

  dynamic get URL {
    // TODO: Implement proper FFI call
    return null;
  }

  dynamic get title {
    // TODO: Implement proper FFI call
    return null;
  }
}

class MLNShapeSource extends MLNSource {
  MLNShapeSource(super._pointer);

  static MLNShapeSource castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNShapeSource(pointer);
  }

  static MLNShapeSource new1() {
    // TODO: Implement proper FFI call
    return MLNShapeSource(ffi.nullptr);
  }

  // New clustering factory method
  static MLNShapeSource createWithClustering(
    String identifier,
    String shape,
    String options,
  ) {
    // For now, return a stub implementation since the FFI bridge needs more work
    // TODO: Implement proper FFI call to native clustering function
    print('Clustering requested for source: $identifier');
    return MLNShapeSource(ffi.nullptr);
  }

  void initWithIdentifier_shape_options_(
    dynamic identifier,
    dynamic shape,
    dynamic options,
  ) {
    // TODO: Implement proper FFI call
  }

  void initWithIdentifier_URL_options_(
    dynamic identifier,
    dynamic url,
    dynamic options,
  ) {
    // TODO: Implement proper FFI call
  }

  set shape(dynamic value) {
    // TODO: Implement proper FFI call
  }
}

class MLNShape {
  final ffi.Pointer<ffi.Void> _pointer;

  MLNShape(this._pointer);

  static MLNShape castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNShape(pointer);
  }

  static dynamic shapeWithData_encoding_error_(
    dynamic data,
    dynamic encoding,
    dynamic error,
  ) {
    // TODO: Implement proper FFI call
    return null;
  }
}

class MLNOfflineStorage {
  final ffi.Pointer<ffi.Void> _pointer;

  MLNOfflineStorage(this._pointer);

  static MLNOfflineStorage castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNOfflineStorage(pointer);
  }

  static MLNOfflineStorage getSharedOfflineStorage() {
    // TODO: Implement proper FFI call to MLNOfflineStorage.sharedOfflineStorage
    // For now, return a stub implementation
    return MLNOfflineStorage(ffi.nullptr);
  }

  dynamic get packs {
    // TODO: Implement proper FFI call
    return null;
  }

  void setMaximumAllowedMapboxTiles(int amount) {
    // TODO: Implement proper FFI call
  }
}

class MLNTilePyramidOfflineRegion {
  final ffi.Pointer<ffi.Void> _pointer;

  MLNTilePyramidOfflineRegion(this._pointer);

  static MLNTilePyramidOfflineRegion castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNTilePyramidOfflineRegion(pointer);
  }

  dynamic get bounds {
    // TODO: Implement proper FFI call
    return null;
  }

  double get minimumZoomLevel {
    // TODO: Implement proper FFI call
    return 0.0;
  }

  double get maximumZoomLevel {
    // TODO: Implement proper FFI call
    return 0.0;
  }
}

class MLNOfflinePack {
  final ffi.Pointer<ffi.Void> _pointer;

  MLNOfflinePack(this._pointer);

  static MLNOfflinePack castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNOfflinePack(pointer);
  }

  dynamic get context {
    // TODO: Implement proper FFI call
    return null;
  }

  dynamic get region {
    // TODO: Implement proper FFI call
    return null;
  }
}

class MLNOfflineRegion {
  final ffi.Pointer<ffi.Void> _pointer;

  MLNOfflineRegion(this._pointer);

  static MLNOfflineRegion castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNOfflineRegion(pointer);
  }
}

class MapLibreRegistry {
  final ffi.Pointer<ffi.Void> _pointer;

  MapLibreRegistry(this._pointer);

  static MapLibreRegistry castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MapLibreRegistry(pointer);
  }

  static ffi.Pointer<ffi.Void>? getMapWithViewId_(int viewId) => null;
}

class Helpers {
  final ffi.Pointer<ffi.Void> _pointer;

  Helpers(this._pointer);

  static Helpers castFrom(ffi.Pointer<ffi.Void> pointer) {
    return Helpers(pointer);
  }
}

// Additional types needed
final class CLLocationCoordinate2D extends ffi.Struct {
  @ffi.Double()
  external double latitude;
  @ffi.Double()
  external double longitude;
}

final class MLNCoordinateBounds extends ffi.Struct {
  external CLLocationCoordinate2D sw;
  external CLLocationCoordinate2D ne;
}

// Additional constants needed
class MLNUserTrackingMode {
  static const int MLNUserTrackingModeNone = 0;
  static const int MLNUserTrackingModeFollow = 1;
  static const int MLNUserTrackingModeFollowWithHeading = 2;
  static const int MLNUserTrackingModeFollowWithCourse = 3;
}

class NSExpression {
  static dynamic expressionWithFormat_(dynamic format) {
    // TODO: Implement proper FFI call
    return null;
  }
}

final class MLNCoordinateQuad extends ffi.Struct {
  external CLLocationCoordinate2D bottomLeft;
  external CLLocationCoordinate2D bottomRight;
  external CLLocationCoordinate2D topLeft;
  external CLLocationCoordinate2D topRight;
}

class NSMutableArray {
  NSMutableArray();

  static NSMutableArray new1() {
    // TODO: Implement proper FFI call
    return NSMutableArray();
  }

  void addObject_(dynamic object) {
    // TODO: Implement proper FFI call
  }

  void init() {
    // TODO: Implement proper FFI call
  }
}

class MLNTileSource extends MLNSource {
  MLNTileSource(super._pointer);

  static MLNTileSource castFrom(ffi.Pointer<ffi.Void> pointer) {
    return MLNTileSource(pointer);
  }

  static bool isInstance(dynamic obj) {
    // TODO: Implement proper FFI call
    return false;
  }

  dynamic get attributionInfos {
    // TODO: Implement proper FFI call
    return null;
  }
}

class objc {
  static dynamic NSDictionary = _NSDictionary();
  static dynamic NSURL = _NSURL();
}

class _NSDictionary {
  dynamic dictionary() {
    // TODO: Implement proper FFI call
    return null;
  }
}

class _NSURL {
  dynamic URLWithString_(dynamic string) {
    // TODO: Implement proper FFI call
    return null;
  }
}

class NSString {
  dynamic toNSString() {
    // TODO: Implement proper FFI call
    return null;
  }

  dynamic dataUsingEncoding_(int encoding) {
    // TODO: Implement proper FFI call
    return null;
  }

  String toDartString() {
    // TODO: Implement proper FFI call
    return '';
  }

  dynamic get absoluteString {
    // TODO: Implement proper FFI call
    return null;
  }

  dynamic get string {
    // TODO: Implement proper FFI call
    return null;
  }

  void release() {
    // TODO: Implement proper FFI call
  }
}

final ffi.Pointer<ffi.Void> nullptr = ffi.nullptr;

class NSMutableDictionary {
  NSMutableDictionary();

  static NSMutableDictionary new1() {
    // TODO: Implement proper FFI call
    return NSMutableDictionary();
  }

  void setObject_forKey_(dynamic object, dynamic key) {
    // TODO: Implement proper FFI call
  }
}

class NSNumber {
  static dynamic numberWithBool_(int value) {
    // TODO: Implement proper FFI call
    return null;
  }

  static dynamic numberWithInt_(int value) {
    // TODO: Implement proper FFI call
    return null;
  }

  static dynamic numberWithDouble_(double value) {
    // TODO: Implement proper FFI call
    return null;
  }
}

// Clustering constants
class MLNShapeSourceOption {
  static const String MLNShapeSourceOptionClustered =
      'MLNShapeSourceOptionClustered';
  static const String MLNShapeSourceOptionClusterRadius =
      'MLNShapeSourceOptionClusterRadius';
  static const String MLNShapeSourceOptionMaximumZoomLevelForClustering =
      'MLNShapeSourceOptionMaximumZoomLevelForClustering';
}

class NSArray {
  NSArray();

  static NSArray new1() {
    // TODO: Implement proper FFI call
    return NSArray();
  }

  int get count {
    // TODO: Implement proper FFI call
    return 0;
  }

  dynamic objectAtIndex_(int index) {
    // TODO: Implement proper FFI call
    return null;
  }

  dynamic get allObjects {
    // TODO: Implement proper FFI call
    return null;
  }
}

// Function lookup for clustering
final _createShapeSourceWithClustering = ffi.DynamicLibrary.open(
  'libmaplibreios.dylib',
).lookupFunction<
  _createShapeSourceWithClustering_C,
  _createShapeSourceWithClustering_Dart
>('createShapeSourceWithClustering');
