// swiftformat:disable all
// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_PIGEON_G_H_
#define PIGEON_PIGEON_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * MapmetricsTileScheme:
 * MAPMETRICS_TILE_SCHEME_XYZ:
 * Slippy map tilenames scheme.
 * MAPMETRICS_TILE_SCHEME_TMS:
 * OSGeo spec scheme.
 *
 * Influences the y direction of the tile coordinates.
 */
typedef enum {
  MAPMETRICS_TILE_SCHEME_XYZ = 0,
  MAPMETRICS_TILE_SCHEME_TMS = 1
} MapmetricsTileScheme;

/**
 * MapmetricsRasterDemEncoding:
 * MAPMETRICS_RASTER_DEM_ENCODING_TERRARIUM:
 * Terrarium format PNG tiles.
 * MAPMETRICS_RASTER_DEM_ENCODING_MAPBOX:
 * Mapbox Terrain RGB tiles.
 * MAPMETRICS_RASTER_DEM_ENCODING_CUSTOM:
 * Decodes tiles using the redFactor, blueFactor, greenFactor, baseShift
 * parameters.
 *
 * The encoding used by this source. Mapbox Terrain RGB is used by default.
 */
typedef enum {
  MAPMETRICS_RASTER_DEM_ENCODING_TERRARIUM = 0,
  MAPMETRICS_RASTER_DEM_ENCODING_MAPBOX = 1,
  MAPMETRICS_RASTER_DEM_ENCODING_CUSTOM = 2
} MapmetricsRasterDemEncoding;

/**
 * MapmetricsCameraChangeReason:
 * MAPMETRICS_CAMERA_CHANGE_REASON_DEVELOPER_ANIMATION:
 * Developer animation.
 * MAPMETRICS_CAMERA_CHANGE_REASON_API_ANIMATION:
 * API animation.
 * MAPMETRICS_CAMERA_CHANGE_REASON_API_GESTURE:
 * API gesture
 *
 * The reason the camera is changing.
 */
typedef enum {
  MAPMETRICS_CAMERA_CHANGE_REASON_DEVELOPER_ANIMATION = 0,
  MAPMETRICS_CAMERA_CHANGE_REASON_API_ANIMATION = 1,
  MAPMETRICS_CAMERA_CHANGE_REASON_API_GESTURE = 2
} MapmetricsCameraChangeReason;

/**
 * MapmetricsLngLat:
 *
 * A longitude/latitude coordinate object.
 */

G_DECLARE_FINAL_TYPE(MapmetricsLngLat, mapmetrics_lng_lat, MAPMETRICS, LNG_LAT, GObject)

/**
 * mapmetrics_lng_lat_new:
 * lng: field in this object.
 * lat: field in this object.
 *
 * Creates a new #LngLat object.
 *
 * Returns: a new #MapmetricsLngLat
 */
MapmetricsLngLat* mapmetrics_lng_lat_new(double lng, double lat);

/**
 * mapmetrics_lng_lat_get_lng
 * @object: a #MapmetricsLngLat.
 *
 * The longitude
 *
 * Returns: the field value.
 */
double mapmetrics_lng_lat_get_lng(MapmetricsLngLat* object);

/**
 * mapmetrics_lng_lat_get_lat
 * @object: a #MapmetricsLngLat.
 *
 * The latitude
 *
 * Returns: the field value.
 */
double mapmetrics_lng_lat_get_lat(MapmetricsLngLat* object);

/**
 * MapmetricsMapOptions:
 *
 * The map options define initial values for the MapLibre map.
 */

G_DECLARE_FINAL_TYPE(MapmetricsMapOptions, mapmetrics_map_options, MAPMETRICS, MAP_OPTIONS, GObject)

/**
 * mapmetrics_map_options_new:
 * style: field in this object.
 * zoom: field in this object.
 * pitch: field in this object.
 * bearing: field in this object.
 * center: field in this object.
 * max_bounds: field in this object.
 * min_zoom: field in this object.
 * max_zoom: field in this object.
 * min_pitch: field in this object.
 * max_pitch: field in this object.
 * gestures: field in this object.
 * android_texture_mode: field in this object.
 *
 * Creates a new #MapOptions object.
 *
 * Returns: a new #MapmetricsMapOptions
 */
MapmetricsMapOptions* mapmetrics_map_options_new(const gchar* style, double zoom, double pitch, double bearing, MapmetricsLngLat* center, MapmetricsLngLatBounds* max_bounds, double min_zoom, double max_zoom, double min_pitch, double max_pitch, MapmetricsMapGestures* gestures, gboolean android_texture_mode);

/**
 * mapmetrics_map_options_get_style
 * @object: a #MapmetricsMapOptions.
 *
 * The URL of the used map style.
 *
 * Returns: the field value.
 */
const gchar* mapmetrics_map_options_get_style(MapmetricsMapOptions* object);

/**
 * mapmetrics_map_options_get_zoom
 * @object: a #MapmetricsMapOptions.
 *
 * The initial zoom level of the map.
 *
 * Returns: the field value.
 */
double mapmetrics_map_options_get_zoom(MapmetricsMapOptions* object);

/**
 * mapmetrics_map_options_get_pitch
 * @object: a #MapmetricsMapOptions.
 *
 * The initial pitch / tilt of the map.
 *
 * Returns: the field value.
 */
double mapmetrics_map_options_get_pitch(MapmetricsMapOptions* object);

/**
 * mapmetrics_map_options_get_bearing
 * @object: a #MapmetricsMapOptions.
 *
 * The initial bearing of the map.
 *
 * Returns: the field value.
 */
double mapmetrics_map_options_get_bearing(MapmetricsMapOptions* object);

/**
 * mapmetrics_map_options_get_center
 * @object: a #MapmetricsMapOptions.
 *
 * The initial center coordinates of the map.
 *
 * Returns: the field value.
 */
MapmetricsLngLat* mapmetrics_map_options_get_center(MapmetricsMapOptions* object);

/**
 * mapmetrics_map_options_get_max_bounds
 * @object: a #MapmetricsMapOptions.
 *
 * The maximum bounding box of the map camera.
 *
 * Returns: the field value.
 */
MapmetricsLngLatBounds* mapmetrics_map_options_get_max_bounds(MapmetricsMapOptions* object);

/**
 * mapmetrics_map_options_get_min_zoom
 * @object: a #MapmetricsMapOptions.
 *
 * The minimum zoom level of the map.
 *
 * Returns: the field value.
 */
double mapmetrics_map_options_get_min_zoom(MapmetricsMapOptions* object);

/**
 * mapmetrics_map_options_get_max_zoom
 * @object: a #MapmetricsMapOptions.
 *
 * The maximum zoom level of the map.
 *
 * Returns: the field value.
 */
double mapmetrics_map_options_get_max_zoom(MapmetricsMapOptions* object);

/**
 * mapmetrics_map_options_get_min_pitch
 * @object: a #MapmetricsMapOptions.
 *
 * The minimum pitch / tilt of the map.
 *
 * Returns: the field value.
 */
double mapmetrics_map_options_get_min_pitch(MapmetricsMapOptions* object);

/**
 * mapmetrics_map_options_get_max_pitch
 * @object: a #MapmetricsMapOptions.
 *
 * The maximum pitch / tilt of the map.
 *
 * Returns: the field value.
 */
double mapmetrics_map_options_get_max_pitch(MapmetricsMapOptions* object);

/**
 * mapmetrics_map_options_get_gestures
 * @object: a #MapmetricsMapOptions.
 *
 * The map gestures.
 *
 * Returns: the field value.
 */
MapmetricsMapGestures* mapmetrics_map_options_get_gestures(MapmetricsMapOptions* object);

/**
 * mapmetrics_map_options_get_android_texture_mode
 * @object: a #MapmetricsMapOptions.
 *
 * Toggle the texture mode on android.
 *
 * Returns: the field value.
 */
gboolean mapmetrics_map_options_get_android_texture_mode(MapmetricsMapOptions* object);

/**
 * MapmetricsMapGestures:
 *
 * Map gestures
 */

G_DECLARE_FINAL_TYPE(MapmetricsMapGestures, mapmetrics_map_gestures, MAPMETRICS, MAP_GESTURES, GObject)

/**
 * mapmetrics_map_gestures_new:
 * rotate: field in this object.
 * pan: field in this object.
 * zoom: field in this object.
 * tilt: field in this object.
 *
 * Creates a new #MapGestures object.
 *
 * Returns: a new #MapmetricsMapGestures
 */
MapmetricsMapGestures* mapmetrics_map_gestures_new(gboolean rotate, gboolean pan, gboolean zoom, gboolean tilt);

/**
 * mapmetrics_map_gestures_get_rotate
 * @object: a #MapmetricsMapGestures.
 *
 * Rotate the map bearing.
 *
 * Returns: the field value.
 */
gboolean mapmetrics_map_gestures_get_rotate(MapmetricsMapGestures* object);

/**
 * mapmetrics_map_gestures_get_pan
 * @object: a #MapmetricsMapGestures.
 *
 * Move the center of the map around.
 *
 * Returns: the field value.
 */
gboolean mapmetrics_map_gestures_get_pan(MapmetricsMapGestures* object);

/**
 * mapmetrics_map_gestures_get_zoom
 * @object: a #MapmetricsMapGestures.
 *
 * Zoom the map in and out.
 *
 * Returns: the field value.
 */
gboolean mapmetrics_map_gestures_get_zoom(MapmetricsMapGestures* object);

/**
 * mapmetrics_map_gestures_get_tilt
 * @object: a #MapmetricsMapGestures.
 *
 * Tilt (pitch) the map camera.
 *
 * Returns: the field value.
 */
gboolean mapmetrics_map_gestures_get_tilt(MapmetricsMapGestures* object);

/**
 * MapmetricsOffset:
 *
 * A pixel location / location on the device screen.
 */

G_DECLARE_FINAL_TYPE(MapmetricsOffset, mapmetrics_offset, MAPMETRICS, OFFSET, GObject)

/**
 * mapmetrics_offset_new:
 * x: field in this object.
 * y: field in this object.
 *
 * Creates a new #Offset object.
 *
 * Returns: a new #MapmetricsOffset
 */
MapmetricsOffset* mapmetrics_offset_new(double x, double y);

/**
 * mapmetrics_offset_get_x
 * @object: a #MapmetricsOffset.
 *
 * The x coordinate
 *
 * Returns: the field value.
 */
double mapmetrics_offset_get_x(MapmetricsOffset* object);

/**
 * mapmetrics_offset_get_y
 * @object: a #MapmetricsOffset.
 *
 * The y coordinate
 *
 * Returns: the field value.
 */
double mapmetrics_offset_get_y(MapmetricsOffset* object);

/**
 * MapmetricsPadding:
 *
 * Camera Padding
 */

G_DECLARE_FINAL_TYPE(MapmetricsPadding, mapmetrics_padding, MAPMETRICS, PADDING, GObject)

/**
 * mapmetrics_padding_new:
 * top: field in this object.
 * bottom: field in this object.
 * left: field in this object.
 * right: field in this object.
 *
 * Creates a new #Padding object.
 *
 * Returns: a new #MapmetricsPadding
 */
MapmetricsPadding* mapmetrics_padding_new(int64_t top, int64_t bottom, int64_t left, int64_t right);

/**
 * mapmetrics_padding_get_top
 * @object: a #MapmetricsPadding.
 *
 * Gets the value of the top field of @object.
 *
 * Returns: the field value.
 */
int64_t mapmetrics_padding_get_top(MapmetricsPadding* object);

/**
 * mapmetrics_padding_get_bottom
 * @object: a #MapmetricsPadding.
 *
 * Gets the value of the bottom field of @object.
 *
 * Returns: the field value.
 */
int64_t mapmetrics_padding_get_bottom(MapmetricsPadding* object);

/**
 * mapmetrics_padding_get_left
 * @object: a #MapmetricsPadding.
 *
 * Gets the value of the left field of @object.
 *
 * Returns: the field value.
 */
int64_t mapmetrics_padding_get_left(MapmetricsPadding* object);

/**
 * mapmetrics_padding_get_right
 * @object: a #MapmetricsPadding.
 *
 * Gets the value of the right field of @object.
 *
 * Returns: the field value.
 */
int64_t mapmetrics_padding_get_right(MapmetricsPadding* object);

/**
 * MapmetricsMapCamera:
 *
 * The current position of the map camera.
 */

G_DECLARE_FINAL_TYPE(MapmetricsMapCamera, mapmetrics_map_camera, MAPMETRICS, MAP_CAMERA, GObject)

/**
 * mapmetrics_map_camera_new:
 * center: field in this object.
 * zoom: field in this object.
 * pitch: field in this object.
 * bearing: field in this object.
 *
 * Creates a new #MapCamera object.
 *
 * Returns: a new #MapmetricsMapCamera
 */
MapmetricsMapCamera* mapmetrics_map_camera_new(MapmetricsLngLat* center, double zoom, double pitch, double bearing);

/**
 * mapmetrics_map_camera_get_center
 * @object: a #MapmetricsMapCamera.
 *
 * Gets the value of the center field of @object.
 *
 * Returns: the field value.
 */
MapmetricsLngLat* mapmetrics_map_camera_get_center(MapmetricsMapCamera* object);

/**
 * mapmetrics_map_camera_get_zoom
 * @object: a #MapmetricsMapCamera.
 *
 * Gets the value of the zoom field of @object.
 *
 * Returns: the field value.
 */
double mapmetrics_map_camera_get_zoom(MapmetricsMapCamera* object);

/**
 * mapmetrics_map_camera_get_pitch
 * @object: a #MapmetricsMapCamera.
 *
 * Gets the value of the pitch field of @object.
 *
 * Returns: the field value.
 */
double mapmetrics_map_camera_get_pitch(MapmetricsMapCamera* object);

/**
 * mapmetrics_map_camera_get_bearing
 * @object: a #MapmetricsMapCamera.
 *
 * Gets the value of the bearing field of @object.
 *
 * Returns: the field value.
 */
double mapmetrics_map_camera_get_bearing(MapmetricsMapCamera* object);

/**
 * MapmetricsLngLatBounds:
 *
 * LatLng bound object
 */

G_DECLARE_FINAL_TYPE(MapmetricsLngLatBounds, mapmetrics_lng_lat_bounds, MAPMETRICS, LNG_LAT_BOUNDS, GObject)

/**
 * mapmetrics_lng_lat_bounds_new:
 * longitude_west: field in this object.
 * longitude_east: field in this object.
 * latitude_south: field in this object.
 * latitude_north: field in this object.
 *
 * Creates a new #LngLatBounds object.
 *
 * Returns: a new #MapmetricsLngLatBounds
 */
MapmetricsLngLatBounds* mapmetrics_lng_lat_bounds_new(double longitude_west, double longitude_east, double latitude_south, double latitude_north);

/**
 * mapmetrics_lng_lat_bounds_get_longitude_west
 * @object: a #MapmetricsLngLatBounds.
 *
 * Gets the value of the longitudeWest field of @object.
 *
 * Returns: the field value.
 */
double mapmetrics_lng_lat_bounds_get_longitude_west(MapmetricsLngLatBounds* object);

/**
 * mapmetrics_lng_lat_bounds_get_longitude_east
 * @object: a #MapmetricsLngLatBounds.
 *
 * Gets the value of the longitudeEast field of @object.
 *
 * Returns: the field value.
 */
double mapmetrics_lng_lat_bounds_get_longitude_east(MapmetricsLngLatBounds* object);

/**
 * mapmetrics_lng_lat_bounds_get_latitude_south
 * @object: a #MapmetricsLngLatBounds.
 *
 * Gets the value of the latitudeSouth field of @object.
 *
 * Returns: the field value.
 */
double mapmetrics_lng_lat_bounds_get_latitude_south(MapmetricsLngLatBounds* object);

/**
 * mapmetrics_lng_lat_bounds_get_latitude_north
 * @object: a #MapmetricsLngLatBounds.
 *
 * Gets the value of the latitudeNorth field of @object.
 *
 * Returns: the field value.
 */
double mapmetrics_lng_lat_bounds_get_latitude_north(MapmetricsLngLatBounds* object);

/**
 * MapmetricsOfflineRegion:
 *
 * Model that describes an offline map region.
 */

G_DECLARE_FINAL_TYPE(MapmetricsOfflineRegion, mapmetrics_offline_region, MAPMETRICS, OFFLINE_REGION, GObject)

/**
 * mapmetrics_offline_region_new:
 * id: field in this object.
 * bounds: field in this object.
 * min_zoom: field in this object.
 * max_zoom: field in this object.
 * pixel_ratio: field in this object.
 * style_url: field in this object.
 *
 * Creates a new #OfflineRegion object.
 *
 * Returns: a new #MapmetricsOfflineRegion
 */
MapmetricsOfflineRegion* mapmetrics_offline_region_new(int64_t id, MapmetricsLngLatBounds* bounds, double min_zoom, double max_zoom, double pixel_ratio, const gchar* style_url);

/**
 * mapmetrics_offline_region_get_id
 * @object: a #MapmetricsOfflineRegion.
 *
 * Gets the value of the id field of @object.
 *
 * Returns: the field value.
 */
int64_t mapmetrics_offline_region_get_id(MapmetricsOfflineRegion* object);

/**
 * mapmetrics_offline_region_get_bounds
 * @object: a #MapmetricsOfflineRegion.
 *
 * Gets the value of the bounds field of @object.
 *
 * Returns: the field value.
 */
MapmetricsLngLatBounds* mapmetrics_offline_region_get_bounds(MapmetricsOfflineRegion* object);

/**
 * mapmetrics_offline_region_get_min_zoom
 * @object: a #MapmetricsOfflineRegion.
 *
 * Gets the value of the minZoom field of @object.
 *
 * Returns: the field value.
 */
double mapmetrics_offline_region_get_min_zoom(MapmetricsOfflineRegion* object);

/**
 * mapmetrics_offline_region_get_max_zoom
 * @object: a #MapmetricsOfflineRegion.
 *
 * Gets the value of the maxZoom field of @object.
 *
 * Returns: the field value.
 */
double mapmetrics_offline_region_get_max_zoom(MapmetricsOfflineRegion* object);

/**
 * mapmetrics_offline_region_get_pixel_ratio
 * @object: a #MapmetricsOfflineRegion.
 *
 * Gets the value of the pixelRatio field of @object.
 *
 * Returns: the field value.
 */
double mapmetrics_offline_region_get_pixel_ratio(MapmetricsOfflineRegion* object);

/**
 * mapmetrics_offline_region_get_style_url
 * @object: a #MapmetricsOfflineRegion.
 *
 * Gets the value of the styleUrl field of @object.
 *
 * Returns: the field value.
 */
const gchar* mapmetrics_offline_region_get_style_url(MapmetricsOfflineRegion* object);

G_DECLARE_FINAL_TYPE(MapmetricsMessageCodec, mapmetrics_message_codec, MAPMETRICS, MESSAGE_CODEC, FlStandardMessageCodec)

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreHostApi, mapmetrics_map_libre_host_api, MAPMETRICS, MAP_LIBRE_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreHostApiResponseHandle, mapmetrics_map_libre_host_api_response_handle, MAPMETRICS, MAP_LIBRE_HOST_API_RESPONSE_HANDLE, GObject)

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreHostApiDisposeResponse, mapmetrics_map_libre_host_api_dispose_response, MAPMETRICS, MAP_LIBRE_HOST_API_DISPOSE_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_host_api_dispose_response_new:
 *
 * Creates a new response to MapLibreHostApi.dispose.
 *
 * Returns: a new #MapmetricsMapLibreHostApiDisposeResponse
 */
MapmetricsMapLibreHostApiDisposeResponse* mapmetrics_map_libre_host_api_dispose_response_new();

/**
 * mapmetrics_map_libre_host_api_dispose_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to MapLibreHostApi.dispose.
 *
 * Returns: a new #MapmetricsMapLibreHostApiDisposeResponse
 */
MapmetricsMapLibreHostApiDisposeResponse* mapmetrics_map_libre_host_api_dispose_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreHostApiGetCameraResponse, mapmetrics_map_libre_host_api_get_camera_response, MAPMETRICS, MAP_LIBRE_HOST_API_GET_CAMERA_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_host_api_get_camera_response_new:
 *
 * Creates a new response to MapLibreHostApi.getCamera.
 *
 * Returns: a new #MapmetricsMapLibreHostApiGetCameraResponse
 */
MapmetricsMapLibreHostApiGetCameraResponse* mapmetrics_map_libre_host_api_get_camera_response_new(MapmetricsMapCamera* return_value);

/**
 * mapmetrics_map_libre_host_api_get_camera_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to MapLibreHostApi.getCamera.
 *
 * Returns: a new #MapmetricsMapLibreHostApiGetCameraResponse
 */
MapmetricsMapLibreHostApiGetCameraResponse* mapmetrics_map_libre_host_api_get_camera_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreHostApiGetZoomLevelResponse, mapmetrics_map_libre_host_api_get_zoom_level_response, MAPMETRICS, MAP_LIBRE_HOST_API_GET_ZOOM_LEVEL_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_host_api_get_zoom_level_response_new:
 *
 * Creates a new response to MapLibreHostApi.getZoomLevel.
 *
 * Returns: a new #MapmetricsMapLibreHostApiGetZoomLevelResponse
 */
MapmetricsMapLibreHostApiGetZoomLevelResponse* mapmetrics_map_libre_host_api_get_zoom_level_response_new(double return_value);

/**
 * mapmetrics_map_libre_host_api_get_zoom_level_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to MapLibreHostApi.getZoomLevel.
 *
 * Returns: a new #MapmetricsMapLibreHostApiGetZoomLevelResponse
 */
MapmetricsMapLibreHostApiGetZoomLevelResponse* mapmetrics_map_libre_host_api_get_zoom_level_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreHostApiGetUserLocationResponse, mapmetrics_map_libre_host_api_get_user_location_response, MAPMETRICS, MAP_LIBRE_HOST_API_GET_USER_LOCATION_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_host_api_get_user_location_response_new:
 *
 * Creates a new response to MapLibreHostApi.getUserLocation.
 *
 * Returns: a new #MapmetricsMapLibreHostApiGetUserLocationResponse
 */
MapmetricsMapLibreHostApiGetUserLocationResponse* mapmetrics_map_libre_host_api_get_user_location_response_new(MapmetricsLngLat* return_value);

/**
 * mapmetrics_map_libre_host_api_get_user_location_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to MapLibreHostApi.getUserLocation.
 *
 * Returns: a new #MapmetricsMapLibreHostApiGetUserLocationResponse
 */
MapmetricsMapLibreHostApiGetUserLocationResponse* mapmetrics_map_libre_host_api_get_user_location_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * MapmetricsMapLibreHostApiVTable:
 *
 * Table of functions exposed by MapLibreHostApi to be implemented by the API provider.
 */
typedef struct {
  MapmetricsMapLibreHostApiDisposeResponse* (*dispose)(gpointer user_data);
  void (*add_fill_layer)(const gchar* id, const gchar* source_id, FlValue* layout, FlValue* paint, const gchar* below_layer_id, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*add_circle_layer)(const gchar* id, const gchar* source_id, FlValue* layout, FlValue* paint, const gchar* below_layer_id, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*add_background_layer)(const gchar* id, FlValue* layout, FlValue* paint, const gchar* below_layer_id, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*add_fill_extrusion_layer)(const gchar* id, const gchar* source_id, FlValue* layout, FlValue* paint, const gchar* below_layer_id, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*add_heatmap_layer)(const gchar* id, const gchar* source_id, FlValue* layout, FlValue* paint, const gchar* below_layer_id, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*add_hillshade_layer)(const gchar* id, const gchar* source_id, FlValue* layout, FlValue* paint, const gchar* below_layer_id, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*add_line_layer)(const gchar* id, const gchar* source_id, FlValue* layout, FlValue* paint, const gchar* below_layer_id, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*add_raster_layer)(const gchar* id, const gchar* source_id, FlValue* layout, FlValue* paint, const gchar* below_layer_id, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*add_symbol_layer)(const gchar* id, const gchar* source_id, FlValue* layout, FlValue* paint, const gchar* below_layer_id, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*load_image)(const gchar* url, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*add_image)(const gchar* id, const uint8_t* bytes, size_t bytes_length, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*add_clustered_geo_json_source)(const gchar* id, const gchar* data, gboolean clustered, double cluster_radius, double cluster_max_zoom, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*test_method)(const gchar* value, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  void (*animate_camera)(double latitude, double longitude, double zoom, double bearing, double pitch, int64_t duration, MapmetricsMapLibreHostApiResponseHandle* response_handle, gpointer user_data);
  MapmetricsMapLibreHostApiGetCameraResponse* (*get_camera)(gpointer user_data);
  MapmetricsMapLibreHostApiGetZoomLevelResponse* (*get_zoom_level)(gpointer user_data);
  MapmetricsMapLibreHostApiGetUserLocationResponse* (*get_user_location)(gpointer user_data);
} MapmetricsMapLibreHostApiVTable;

/**
 * mapmetrics_map_libre_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the MapLibreHostApi API.
 */
void mapmetrics_map_libre_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const MapmetricsMapLibreHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * mapmetrics_map_libre_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the MapLibreHostApi API.
 */
void mapmetrics_map_libre_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * mapmetrics_map_libre_host_api_respond_add_fill_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.addFillLayer. 
 */
void mapmetrics_map_libre_host_api_respond_add_fill_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_add_fill_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.addFillLayer. 
 */
void mapmetrics_map_libre_host_api_respond_error_add_fill_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_add_circle_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.addCircleLayer. 
 */
void mapmetrics_map_libre_host_api_respond_add_circle_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_add_circle_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.addCircleLayer. 
 */
void mapmetrics_map_libre_host_api_respond_error_add_circle_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_add_background_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.addBackgroundLayer. 
 */
void mapmetrics_map_libre_host_api_respond_add_background_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_add_background_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.addBackgroundLayer. 
 */
void mapmetrics_map_libre_host_api_respond_error_add_background_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_add_fill_extrusion_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.addFillExtrusionLayer. 
 */
void mapmetrics_map_libre_host_api_respond_add_fill_extrusion_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_add_fill_extrusion_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.addFillExtrusionLayer. 
 */
void mapmetrics_map_libre_host_api_respond_error_add_fill_extrusion_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_add_heatmap_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.addHeatmapLayer. 
 */
void mapmetrics_map_libre_host_api_respond_add_heatmap_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_add_heatmap_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.addHeatmapLayer. 
 */
void mapmetrics_map_libre_host_api_respond_error_add_heatmap_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_add_hillshade_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.addHillshadeLayer. 
 */
void mapmetrics_map_libre_host_api_respond_add_hillshade_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_add_hillshade_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.addHillshadeLayer. 
 */
void mapmetrics_map_libre_host_api_respond_error_add_hillshade_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_add_line_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.addLineLayer. 
 */
void mapmetrics_map_libre_host_api_respond_add_line_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_add_line_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.addLineLayer. 
 */
void mapmetrics_map_libre_host_api_respond_error_add_line_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_add_raster_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.addRasterLayer. 
 */
void mapmetrics_map_libre_host_api_respond_add_raster_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_add_raster_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.addRasterLayer. 
 */
void mapmetrics_map_libre_host_api_respond_error_add_raster_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_add_symbol_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.addSymbolLayer. 
 */
void mapmetrics_map_libre_host_api_respond_add_symbol_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_add_symbol_layer:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.addSymbolLayer. 
 */
void mapmetrics_map_libre_host_api_respond_error_add_symbol_layer(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_load_image:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 * @return_value_length: (allow-none): location to write length of @return_value or %NULL to ignore.
 *
 * Responds to MapLibreHostApi.loadImage. 
 */
void mapmetrics_map_libre_host_api_respond_load_image(MapmetricsMapLibreHostApiResponseHandle* response_handle, const uint8_t* return_value, size_t return_value_length);

/**
 * mapmetrics_map_libre_host_api_respond_error_load_image:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.loadImage. 
 */
void mapmetrics_map_libre_host_api_respond_error_load_image(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_add_image:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.addImage. 
 */
void mapmetrics_map_libre_host_api_respond_add_image(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_add_image:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.addImage. 
 */
void mapmetrics_map_libre_host_api_respond_error_add_image(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_add_clustered_geo_json_source:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.addClusteredGeoJsonSource. 
 */
void mapmetrics_map_libre_host_api_respond_add_clustered_geo_json_source(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_add_clustered_geo_json_source:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.addClusteredGeoJsonSource. 
 */
void mapmetrics_map_libre_host_api_respond_error_add_clustered_geo_json_source(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_test_method:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.testMethod. 
 */
void mapmetrics_map_libre_host_api_respond_test_method(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_test_method:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.testMethod. 
 */
void mapmetrics_map_libre_host_api_respond_error_test_method(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_map_libre_host_api_respond_animate_camera:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 *
 * Responds to MapLibreHostApi.animateCamera. 
 */
void mapmetrics_map_libre_host_api_respond_animate_camera(MapmetricsMapLibreHostApiResponseHandle* response_handle);

/**
 * mapmetrics_map_libre_host_api_respond_error_animate_camera:
 * @response_handle: a #MapmetricsMapLibreHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MapLibreHostApi.animateCamera. 
 */
void mapmetrics_map_libre_host_api_respond_error_animate_camera(MapmetricsMapLibreHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreFlutterApiGetOptionsResponse, mapmetrics_map_libre_flutter_api_get_options_response, MAPMETRICS, MAP_LIBRE_FLUTTER_API_GET_OPTIONS_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_flutter_api_get_options_response_is_error:
 * @response: a #MapmetricsMapLibreFlutterApiGetOptionsResponse.
 *
 * Checks if a response to MapLibreFlutterApi.getOptions is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean mapmetrics_map_libre_flutter_api_get_options_response_is_error(MapmetricsMapLibreFlutterApiGetOptionsResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_get_options_response_get_error_code:
 * @response: a #MapmetricsMapLibreFlutterApiGetOptionsResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* mapmetrics_map_libre_flutter_api_get_options_response_get_error_code(MapmetricsMapLibreFlutterApiGetOptionsResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_get_options_response_get_error_message:
 * @response: a #MapmetricsMapLibreFlutterApiGetOptionsResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* mapmetrics_map_libre_flutter_api_get_options_response_get_error_message(MapmetricsMapLibreFlutterApiGetOptionsResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_get_options_response_get_error_details:
 * @response: a #MapmetricsMapLibreFlutterApiGetOptionsResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* mapmetrics_map_libre_flutter_api_get_options_response_get_error_details(MapmetricsMapLibreFlutterApiGetOptionsResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_get_options_response_get_return_value:
 * @response: a #MapmetricsMapLibreFlutterApiGetOptionsResponse.
 *
 * Get the return value for this response.
 *
 * Returns: a return value.
 */
MapmetricsMapOptions* mapmetrics_map_libre_flutter_api_get_options_response_get_return_value(MapmetricsMapLibreFlutterApiGetOptionsResponse* response);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreFlutterApiOnStyleLoadedResponse, mapmetrics_map_libre_flutter_api_on_style_loaded_response, MAPMETRICS, MAP_LIBRE_FLUTTER_API_ON_STYLE_LOADED_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_flutter_api_on_style_loaded_response_is_error:
 * @response: a #MapmetricsMapLibreFlutterApiOnStyleLoadedResponse.
 *
 * Checks if a response to MapLibreFlutterApi.onStyleLoaded is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean mapmetrics_map_libre_flutter_api_on_style_loaded_response_is_error(MapmetricsMapLibreFlutterApiOnStyleLoadedResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_style_loaded_response_get_error_code:
 * @response: a #MapmetricsMapLibreFlutterApiOnStyleLoadedResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_style_loaded_response_get_error_code(MapmetricsMapLibreFlutterApiOnStyleLoadedResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_style_loaded_response_get_error_message:
 * @response: a #MapmetricsMapLibreFlutterApiOnStyleLoadedResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_style_loaded_response_get_error_message(MapmetricsMapLibreFlutterApiOnStyleLoadedResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_style_loaded_response_get_error_details:
 * @response: a #MapmetricsMapLibreFlutterApiOnStyleLoadedResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* mapmetrics_map_libre_flutter_api_on_style_loaded_response_get_error_details(MapmetricsMapLibreFlutterApiOnStyleLoadedResponse* response);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreFlutterApiOnMapReadyResponse, mapmetrics_map_libre_flutter_api_on_map_ready_response, MAPMETRICS, MAP_LIBRE_FLUTTER_API_ON_MAP_READY_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_flutter_api_on_map_ready_response_is_error:
 * @response: a #MapmetricsMapLibreFlutterApiOnMapReadyResponse.
 *
 * Checks if a response to MapLibreFlutterApi.onMapReady is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean mapmetrics_map_libre_flutter_api_on_map_ready_response_is_error(MapmetricsMapLibreFlutterApiOnMapReadyResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_map_ready_response_get_error_code:
 * @response: a #MapmetricsMapLibreFlutterApiOnMapReadyResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_map_ready_response_get_error_code(MapmetricsMapLibreFlutterApiOnMapReadyResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_map_ready_response_get_error_message:
 * @response: a #MapmetricsMapLibreFlutterApiOnMapReadyResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_map_ready_response_get_error_message(MapmetricsMapLibreFlutterApiOnMapReadyResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_map_ready_response_get_error_details:
 * @response: a #MapmetricsMapLibreFlutterApiOnMapReadyResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* mapmetrics_map_libre_flutter_api_on_map_ready_response_get_error_details(MapmetricsMapLibreFlutterApiOnMapReadyResponse* response);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreFlutterApiOnClickResponse, mapmetrics_map_libre_flutter_api_on_click_response, MAPMETRICS, MAP_LIBRE_FLUTTER_API_ON_CLICK_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_flutter_api_on_click_response_is_error:
 * @response: a #MapmetricsMapLibreFlutterApiOnClickResponse.
 *
 * Checks if a response to MapLibreFlutterApi.onClick is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean mapmetrics_map_libre_flutter_api_on_click_response_is_error(MapmetricsMapLibreFlutterApiOnClickResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_click_response_get_error_code:
 * @response: a #MapmetricsMapLibreFlutterApiOnClickResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_click_response_get_error_code(MapmetricsMapLibreFlutterApiOnClickResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_click_response_get_error_message:
 * @response: a #MapmetricsMapLibreFlutterApiOnClickResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_click_response_get_error_message(MapmetricsMapLibreFlutterApiOnClickResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_click_response_get_error_details:
 * @response: a #MapmetricsMapLibreFlutterApiOnClickResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* mapmetrics_map_libre_flutter_api_on_click_response_get_error_details(MapmetricsMapLibreFlutterApiOnClickResponse* response);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreFlutterApiOnIdleResponse, mapmetrics_map_libre_flutter_api_on_idle_response, MAPMETRICS, MAP_LIBRE_FLUTTER_API_ON_IDLE_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_flutter_api_on_idle_response_is_error:
 * @response: a #MapmetricsMapLibreFlutterApiOnIdleResponse.
 *
 * Checks if a response to MapLibreFlutterApi.onIdle is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean mapmetrics_map_libre_flutter_api_on_idle_response_is_error(MapmetricsMapLibreFlutterApiOnIdleResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_idle_response_get_error_code:
 * @response: a #MapmetricsMapLibreFlutterApiOnIdleResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_idle_response_get_error_code(MapmetricsMapLibreFlutterApiOnIdleResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_idle_response_get_error_message:
 * @response: a #MapmetricsMapLibreFlutterApiOnIdleResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_idle_response_get_error_message(MapmetricsMapLibreFlutterApiOnIdleResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_idle_response_get_error_details:
 * @response: a #MapmetricsMapLibreFlutterApiOnIdleResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* mapmetrics_map_libre_flutter_api_on_idle_response_get_error_details(MapmetricsMapLibreFlutterApiOnIdleResponse* response);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreFlutterApiOnCameraIdleResponse, mapmetrics_map_libre_flutter_api_on_camera_idle_response, MAPMETRICS, MAP_LIBRE_FLUTTER_API_ON_CAMERA_IDLE_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_flutter_api_on_camera_idle_response_is_error:
 * @response: a #MapmetricsMapLibreFlutterApiOnCameraIdleResponse.
 *
 * Checks if a response to MapLibreFlutterApi.onCameraIdle is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean mapmetrics_map_libre_flutter_api_on_camera_idle_response_is_error(MapmetricsMapLibreFlutterApiOnCameraIdleResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_camera_idle_response_get_error_code:
 * @response: a #MapmetricsMapLibreFlutterApiOnCameraIdleResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_camera_idle_response_get_error_code(MapmetricsMapLibreFlutterApiOnCameraIdleResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_camera_idle_response_get_error_message:
 * @response: a #MapmetricsMapLibreFlutterApiOnCameraIdleResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_camera_idle_response_get_error_message(MapmetricsMapLibreFlutterApiOnCameraIdleResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_camera_idle_response_get_error_details:
 * @response: a #MapmetricsMapLibreFlutterApiOnCameraIdleResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* mapmetrics_map_libre_flutter_api_on_camera_idle_response_get_error_details(MapmetricsMapLibreFlutterApiOnCameraIdleResponse* response);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreFlutterApiOnSecondaryClickResponse, mapmetrics_map_libre_flutter_api_on_secondary_click_response, MAPMETRICS, MAP_LIBRE_FLUTTER_API_ON_SECONDARY_CLICK_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_flutter_api_on_secondary_click_response_is_error:
 * @response: a #MapmetricsMapLibreFlutterApiOnSecondaryClickResponse.
 *
 * Checks if a response to MapLibreFlutterApi.onSecondaryClick is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean mapmetrics_map_libre_flutter_api_on_secondary_click_response_is_error(MapmetricsMapLibreFlutterApiOnSecondaryClickResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_secondary_click_response_get_error_code:
 * @response: a #MapmetricsMapLibreFlutterApiOnSecondaryClickResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_secondary_click_response_get_error_code(MapmetricsMapLibreFlutterApiOnSecondaryClickResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_secondary_click_response_get_error_message:
 * @response: a #MapmetricsMapLibreFlutterApiOnSecondaryClickResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_secondary_click_response_get_error_message(MapmetricsMapLibreFlutterApiOnSecondaryClickResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_secondary_click_response_get_error_details:
 * @response: a #MapmetricsMapLibreFlutterApiOnSecondaryClickResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* mapmetrics_map_libre_flutter_api_on_secondary_click_response_get_error_details(MapmetricsMapLibreFlutterApiOnSecondaryClickResponse* response);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreFlutterApiOnDoubleClickResponse, mapmetrics_map_libre_flutter_api_on_double_click_response, MAPMETRICS, MAP_LIBRE_FLUTTER_API_ON_DOUBLE_CLICK_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_flutter_api_on_double_click_response_is_error:
 * @response: a #MapmetricsMapLibreFlutterApiOnDoubleClickResponse.
 *
 * Checks if a response to MapLibreFlutterApi.onDoubleClick is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean mapmetrics_map_libre_flutter_api_on_double_click_response_is_error(MapmetricsMapLibreFlutterApiOnDoubleClickResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_double_click_response_get_error_code:
 * @response: a #MapmetricsMapLibreFlutterApiOnDoubleClickResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_double_click_response_get_error_code(MapmetricsMapLibreFlutterApiOnDoubleClickResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_double_click_response_get_error_message:
 * @response: a #MapmetricsMapLibreFlutterApiOnDoubleClickResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_double_click_response_get_error_message(MapmetricsMapLibreFlutterApiOnDoubleClickResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_double_click_response_get_error_details:
 * @response: a #MapmetricsMapLibreFlutterApiOnDoubleClickResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* mapmetrics_map_libre_flutter_api_on_double_click_response_get_error_details(MapmetricsMapLibreFlutterApiOnDoubleClickResponse* response);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreFlutterApiOnLongClickResponse, mapmetrics_map_libre_flutter_api_on_long_click_response, MAPMETRICS, MAP_LIBRE_FLUTTER_API_ON_LONG_CLICK_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_flutter_api_on_long_click_response_is_error:
 * @response: a #MapmetricsMapLibreFlutterApiOnLongClickResponse.
 *
 * Checks if a response to MapLibreFlutterApi.onLongClick is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean mapmetrics_map_libre_flutter_api_on_long_click_response_is_error(MapmetricsMapLibreFlutterApiOnLongClickResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_long_click_response_get_error_code:
 * @response: a #MapmetricsMapLibreFlutterApiOnLongClickResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_long_click_response_get_error_code(MapmetricsMapLibreFlutterApiOnLongClickResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_long_click_response_get_error_message:
 * @response: a #MapmetricsMapLibreFlutterApiOnLongClickResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_long_click_response_get_error_message(MapmetricsMapLibreFlutterApiOnLongClickResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_long_click_response_get_error_details:
 * @response: a #MapmetricsMapLibreFlutterApiOnLongClickResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* mapmetrics_map_libre_flutter_api_on_long_click_response_get_error_details(MapmetricsMapLibreFlutterApiOnLongClickResponse* response);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreFlutterApiOnMoveCameraResponse, mapmetrics_map_libre_flutter_api_on_move_camera_response, MAPMETRICS, MAP_LIBRE_FLUTTER_API_ON_MOVE_CAMERA_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_flutter_api_on_move_camera_response_is_error:
 * @response: a #MapmetricsMapLibreFlutterApiOnMoveCameraResponse.
 *
 * Checks if a response to MapLibreFlutterApi.onMoveCamera is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean mapmetrics_map_libre_flutter_api_on_move_camera_response_is_error(MapmetricsMapLibreFlutterApiOnMoveCameraResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_move_camera_response_get_error_code:
 * @response: a #MapmetricsMapLibreFlutterApiOnMoveCameraResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_move_camera_response_get_error_code(MapmetricsMapLibreFlutterApiOnMoveCameraResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_move_camera_response_get_error_message:
 * @response: a #MapmetricsMapLibreFlutterApiOnMoveCameraResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_move_camera_response_get_error_message(MapmetricsMapLibreFlutterApiOnMoveCameraResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_move_camera_response_get_error_details:
 * @response: a #MapmetricsMapLibreFlutterApiOnMoveCameraResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* mapmetrics_map_libre_flutter_api_on_move_camera_response_get_error_details(MapmetricsMapLibreFlutterApiOnMoveCameraResponse* response);

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreFlutterApiOnStartMoveCameraResponse, mapmetrics_map_libre_flutter_api_on_start_move_camera_response, MAPMETRICS, MAP_LIBRE_FLUTTER_API_ON_START_MOVE_CAMERA_RESPONSE, GObject)

/**
 * mapmetrics_map_libre_flutter_api_on_start_move_camera_response_is_error:
 * @response: a #MapmetricsMapLibreFlutterApiOnStartMoveCameraResponse.
 *
 * Checks if a response to MapLibreFlutterApi.onStartMoveCamera is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean mapmetrics_map_libre_flutter_api_on_start_move_camera_response_is_error(MapmetricsMapLibreFlutterApiOnStartMoveCameraResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_start_move_camera_response_get_error_code:
 * @response: a #MapmetricsMapLibreFlutterApiOnStartMoveCameraResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_start_move_camera_response_get_error_code(MapmetricsMapLibreFlutterApiOnStartMoveCameraResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_start_move_camera_response_get_error_message:
 * @response: a #MapmetricsMapLibreFlutterApiOnStartMoveCameraResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* mapmetrics_map_libre_flutter_api_on_start_move_camera_response_get_error_message(MapmetricsMapLibreFlutterApiOnStartMoveCameraResponse* response);

/**
 * mapmetrics_map_libre_flutter_api_on_start_move_camera_response_get_error_details:
 * @response: a #MapmetricsMapLibreFlutterApiOnStartMoveCameraResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* mapmetrics_map_libre_flutter_api_on_start_move_camera_response_get_error_details(MapmetricsMapLibreFlutterApiOnStartMoveCameraResponse* response);

/**
 * MapmetricsMapLibreFlutterApi:
 *
 */

G_DECLARE_FINAL_TYPE(MapmetricsMapLibreFlutterApi, mapmetrics_map_libre_flutter_api, MAPMETRICS, MAP_LIBRE_FLUTTER_API, GObject)

/**
 * mapmetrics_map_libre_flutter_api_new:
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Creates a new object to access the MapLibreFlutterApi API.
 *
 * Returns: a new #MapmetricsMapLibreFlutterApi
 */
MapmetricsMapLibreFlutterApi* mapmetrics_map_libre_flutter_api_new(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * mapmetrics_map_libre_flutter_api_get_options:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Get the map options from dart.
 */
void mapmetrics_map_libre_flutter_api_get_options(MapmetricsMapLibreFlutterApi* api, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * mapmetrics_map_libre_flutter_api_get_options_finish:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a mapmetrics_map_libre_flutter_api_get_options() call.
 *
 * Returns: a #MapmetricsMapLibreFlutterApiGetOptionsResponse or %NULL on error.
 */
MapmetricsMapLibreFlutterApiGetOptionsResponse* mapmetrics_map_libre_flutter_api_get_options_finish(MapmetricsMapLibreFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * mapmetrics_map_libre_flutter_api_on_style_loaded:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Callback for when the style has been loaded.
 */
void mapmetrics_map_libre_flutter_api_on_style_loaded(MapmetricsMapLibreFlutterApi* api, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * mapmetrics_map_libre_flutter_api_on_style_loaded_finish:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a mapmetrics_map_libre_flutter_api_on_style_loaded() call.
 *
 * Returns: a #MapmetricsMapLibreFlutterApiOnStyleLoadedResponse or %NULL on error.
 */
MapmetricsMapLibreFlutterApiOnStyleLoadedResponse* mapmetrics_map_libre_flutter_api_on_style_loaded_finish(MapmetricsMapLibreFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * mapmetrics_map_libre_flutter_api_on_map_ready:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Callback for when the map is ready and can be used.
 */
void mapmetrics_map_libre_flutter_api_on_map_ready(MapmetricsMapLibreFlutterApi* api, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * mapmetrics_map_libre_flutter_api_on_map_ready_finish:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a mapmetrics_map_libre_flutter_api_on_map_ready() call.
 *
 * Returns: a #MapmetricsMapLibreFlutterApiOnMapReadyResponse or %NULL on error.
 */
MapmetricsMapLibreFlutterApiOnMapReadyResponse* mapmetrics_map_libre_flutter_api_on_map_ready_finish(MapmetricsMapLibreFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * mapmetrics_map_libre_flutter_api_on_click:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @point: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Callback when the user clicks on the map.
 */
void mapmetrics_map_libre_flutter_api_on_click(MapmetricsMapLibreFlutterApi* api, MapmetricsLngLat* point, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * mapmetrics_map_libre_flutter_api_on_click_finish:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a mapmetrics_map_libre_flutter_api_on_click() call.
 *
 * Returns: a #MapmetricsMapLibreFlutterApiOnClickResponse or %NULL on error.
 */
MapmetricsMapLibreFlutterApiOnClickResponse* mapmetrics_map_libre_flutter_api_on_click_finish(MapmetricsMapLibreFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * mapmetrics_map_libre_flutter_api_on_idle:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Callback when the map idles.
 */
void mapmetrics_map_libre_flutter_api_on_idle(MapmetricsMapLibreFlutterApi* api, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * mapmetrics_map_libre_flutter_api_on_idle_finish:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a mapmetrics_map_libre_flutter_api_on_idle() call.
 *
 * Returns: a #MapmetricsMapLibreFlutterApiOnIdleResponse or %NULL on error.
 */
MapmetricsMapLibreFlutterApiOnIdleResponse* mapmetrics_map_libre_flutter_api_on_idle_finish(MapmetricsMapLibreFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * mapmetrics_map_libre_flutter_api_on_camera_idle:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Callback when the map camera idles.
 */
void mapmetrics_map_libre_flutter_api_on_camera_idle(MapmetricsMapLibreFlutterApi* api, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * mapmetrics_map_libre_flutter_api_on_camera_idle_finish:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a mapmetrics_map_libre_flutter_api_on_camera_idle() call.
 *
 * Returns: a #MapmetricsMapLibreFlutterApiOnCameraIdleResponse or %NULL on error.
 */
MapmetricsMapLibreFlutterApiOnCameraIdleResponse* mapmetrics_map_libre_flutter_api_on_camera_idle_finish(MapmetricsMapLibreFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * mapmetrics_map_libre_flutter_api_on_secondary_click:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @point: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Callback when the user performs a secondary click on the map
 * (e.g. by default a click with the right mouse button).
 */
void mapmetrics_map_libre_flutter_api_on_secondary_click(MapmetricsMapLibreFlutterApi* api, MapmetricsLngLat* point, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * mapmetrics_map_libre_flutter_api_on_secondary_click_finish:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a mapmetrics_map_libre_flutter_api_on_secondary_click() call.
 *
 * Returns: a #MapmetricsMapLibreFlutterApiOnSecondaryClickResponse or %NULL on error.
 */
MapmetricsMapLibreFlutterApiOnSecondaryClickResponse* mapmetrics_map_libre_flutter_api_on_secondary_click_finish(MapmetricsMapLibreFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * mapmetrics_map_libre_flutter_api_on_double_click:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @point: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Callback when the user performs a double click on the map.
 */
void mapmetrics_map_libre_flutter_api_on_double_click(MapmetricsMapLibreFlutterApi* api, MapmetricsLngLat* point, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * mapmetrics_map_libre_flutter_api_on_double_click_finish:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a mapmetrics_map_libre_flutter_api_on_double_click() call.
 *
 * Returns: a #MapmetricsMapLibreFlutterApiOnDoubleClickResponse or %NULL on error.
 */
MapmetricsMapLibreFlutterApiOnDoubleClickResponse* mapmetrics_map_libre_flutter_api_on_double_click_finish(MapmetricsMapLibreFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * mapmetrics_map_libre_flutter_api_on_long_click:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @point: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Callback when the user performs a long lasting click on the map.
 */
void mapmetrics_map_libre_flutter_api_on_long_click(MapmetricsMapLibreFlutterApi* api, MapmetricsLngLat* point, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * mapmetrics_map_libre_flutter_api_on_long_click_finish:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a mapmetrics_map_libre_flutter_api_on_long_click() call.
 *
 * Returns: a #MapmetricsMapLibreFlutterApiOnLongClickResponse or %NULL on error.
 */
MapmetricsMapLibreFlutterApiOnLongClickResponse* mapmetrics_map_libre_flutter_api_on_long_click_finish(MapmetricsMapLibreFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * mapmetrics_map_libre_flutter_api_on_move_camera:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @camera: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Callback when the map camera changes.
 */
void mapmetrics_map_libre_flutter_api_on_move_camera(MapmetricsMapLibreFlutterApi* api, MapmetricsMapCamera* camera, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * mapmetrics_map_libre_flutter_api_on_move_camera_finish:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a mapmetrics_map_libre_flutter_api_on_move_camera() call.
 *
 * Returns: a #MapmetricsMapLibreFlutterApiOnMoveCameraResponse or %NULL on error.
 */
MapmetricsMapLibreFlutterApiOnMoveCameraResponse* mapmetrics_map_libre_flutter_api_on_move_camera_finish(MapmetricsMapLibreFlutterApi* api, GAsyncResult* result, GError** error);

/**
 * mapmetrics_map_libre_flutter_api_on_start_move_camera:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @reason: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Callback when the map camera starts changing.
 */
void mapmetrics_map_libre_flutter_api_on_start_move_camera(MapmetricsMapLibreFlutterApi* api, MapmetricsCameraChangeReason reason, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * mapmetrics_map_libre_flutter_api_on_start_move_camera_finish:
 * @api: a #MapmetricsMapLibreFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a mapmetrics_map_libre_flutter_api_on_start_move_camera() call.
 *
 * Returns: a #MapmetricsMapLibreFlutterApiOnStartMoveCameraResponse or %NULL on error.
 */
MapmetricsMapLibreFlutterApiOnStartMoveCameraResponse* mapmetrics_map_libre_flutter_api_on_start_move_camera_finish(MapmetricsMapLibreFlutterApi* api, GAsyncResult* result, GError** error);

G_DECLARE_FINAL_TYPE(MapmetricsPermissionManagerHostApi, mapmetrics_permission_manager_host_api, MAPMETRICS, PERMISSION_MANAGER_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(MapmetricsPermissionManagerHostApiResponseHandle, mapmetrics_permission_manager_host_api_response_handle, MAPMETRICS, PERMISSION_MANAGER_HOST_API_RESPONSE_HANDLE, GObject)

/**
 * MapmetricsPermissionManagerHostApiVTable:
 *
 * Table of functions exposed by PermissionManagerHostApi to be implemented by the API provider.
 */
typedef struct {
  void (*request_location_permissions)(const gchar* explanation, MapmetricsPermissionManagerHostApiResponseHandle* response_handle, gpointer user_data);
} MapmetricsPermissionManagerHostApiVTable;

/**
 * mapmetrics_permission_manager_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the PermissionManagerHostApi API.
 */
void mapmetrics_permission_manager_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const MapmetricsPermissionManagerHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * mapmetrics_permission_manager_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the PermissionManagerHostApi API.
 */
void mapmetrics_permission_manager_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * mapmetrics_permission_manager_host_api_respond_request_location_permissions:
 * @response_handle: a #MapmetricsPermissionManagerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to PermissionManagerHostApi.requestLocationPermissions. 
 */
void mapmetrics_permission_manager_host_api_respond_request_location_permissions(MapmetricsPermissionManagerHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * mapmetrics_permission_manager_host_api_respond_error_request_location_permissions:
 * @response_handle: a #MapmetricsPermissionManagerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to PermissionManagerHostApi.requestLocationPermissions. 
 */
void mapmetrics_permission_manager_host_api_respond_error_request_location_permissions(MapmetricsPermissionManagerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(MapmetricsOfflineManagerHostApi, mapmetrics_offline_manager_host_api, MAPMETRICS, OFFLINE_MANAGER_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(MapmetricsOfflineManagerHostApiResponseHandle, mapmetrics_offline_manager_host_api_response_handle, MAPMETRICS, OFFLINE_MANAGER_HOST_API_RESPONSE_HANDLE, GObject)

/**
 * MapmetricsOfflineManagerHostApiVTable:
 *
 * Table of functions exposed by OfflineManagerHostApi to be implemented by the API provider.
 */
typedef struct {
  void (*clear_ambient_cache)(MapmetricsOfflineManagerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*invalidate_ambient_cache)(MapmetricsOfflineManagerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*reset_database)(MapmetricsOfflineManagerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_maximum_ambient_cache_size)(int64_t bytes, MapmetricsOfflineManagerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*download_region)(const gchar* map_style_url, MapmetricsLngLatBounds* bounds, double min_zoom, double max_zoom, double pixel_density, const gchar* metadata, MapmetricsOfflineManagerHostApiResponseHandle* response_handle, gpointer user_data);
} MapmetricsOfflineManagerHostApiVTable;

/**
 * mapmetrics_offline_manager_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the OfflineManagerHostApi API.
 */
void mapmetrics_offline_manager_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const MapmetricsOfflineManagerHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * mapmetrics_offline_manager_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the OfflineManagerHostApi API.
 */
void mapmetrics_offline_manager_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * mapmetrics_offline_manager_host_api_respond_clear_ambient_cache:
 * @response_handle: a #MapmetricsOfflineManagerHostApiResponseHandle.
 *
 * Responds to OfflineManagerHostApi.clearAmbientCache. 
 */
void mapmetrics_offline_manager_host_api_respond_clear_ambient_cache(MapmetricsOfflineManagerHostApiResponseHandle* response_handle);

/**
 * mapmetrics_offline_manager_host_api_respond_error_clear_ambient_cache:
 * @response_handle: a #MapmetricsOfflineManagerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to OfflineManagerHostApi.clearAmbientCache. 
 */
void mapmetrics_offline_manager_host_api_respond_error_clear_ambient_cache(MapmetricsOfflineManagerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_offline_manager_host_api_respond_invalidate_ambient_cache:
 * @response_handle: a #MapmetricsOfflineManagerHostApiResponseHandle.
 *
 * Responds to OfflineManagerHostApi.invalidateAmbientCache. 
 */
void mapmetrics_offline_manager_host_api_respond_invalidate_ambient_cache(MapmetricsOfflineManagerHostApiResponseHandle* response_handle);

/**
 * mapmetrics_offline_manager_host_api_respond_error_invalidate_ambient_cache:
 * @response_handle: a #MapmetricsOfflineManagerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to OfflineManagerHostApi.invalidateAmbientCache. 
 */
void mapmetrics_offline_manager_host_api_respond_error_invalidate_ambient_cache(MapmetricsOfflineManagerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_offline_manager_host_api_respond_reset_database:
 * @response_handle: a #MapmetricsOfflineManagerHostApiResponseHandle.
 *
 * Responds to OfflineManagerHostApi.resetDatabase. 
 */
void mapmetrics_offline_manager_host_api_respond_reset_database(MapmetricsOfflineManagerHostApiResponseHandle* response_handle);

/**
 * mapmetrics_offline_manager_host_api_respond_error_reset_database:
 * @response_handle: a #MapmetricsOfflineManagerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to OfflineManagerHostApi.resetDatabase. 
 */
void mapmetrics_offline_manager_host_api_respond_error_reset_database(MapmetricsOfflineManagerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_offline_manager_host_api_respond_set_maximum_ambient_cache_size:
 * @response_handle: a #MapmetricsOfflineManagerHostApiResponseHandle.
 *
 * Responds to OfflineManagerHostApi.setMaximumAmbientCacheSize. 
 */
void mapmetrics_offline_manager_host_api_respond_set_maximum_ambient_cache_size(MapmetricsOfflineManagerHostApiResponseHandle* response_handle);

/**
 * mapmetrics_offline_manager_host_api_respond_error_set_maximum_ambient_cache_size:
 * @response_handle: a #MapmetricsOfflineManagerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to OfflineManagerHostApi.setMaximumAmbientCacheSize. 
 */
void mapmetrics_offline_manager_host_api_respond_error_set_maximum_ambient_cache_size(MapmetricsOfflineManagerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * mapmetrics_offline_manager_host_api_respond_download_region:
 * @response_handle: a #MapmetricsOfflineManagerHostApiResponseHandle.
 *
 * Responds to OfflineManagerHostApi.downloadRegion. 
 */
void mapmetrics_offline_manager_host_api_respond_download_region(MapmetricsOfflineManagerHostApiResponseHandle* response_handle);

/**
 * mapmetrics_offline_manager_host_api_respond_error_download_region:
 * @response_handle: a #MapmetricsOfflineManagerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to OfflineManagerHostApi.downloadRegion. 
 */
void mapmetrics_offline_manager_host_api_respond_error_download_region(MapmetricsOfflineManagerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_END_DECLS

#endif  // PIGEON_PIGEON_G_H_
